// NutriDesi food database — Indian items with Hinglish aliases.
// Aliases are the single biggest lever on parse accuracy. Expand these over time.
// Fields: id, name, aliases[], unit, kcal, protein(p), carbs(c), fat(f), fibre(fb), grams(g)?, modifier?

const FOODS = [
  { id: 1,  name: "Roti / Chapati",       aliases: ["roti","chapati","phulka","chappati","fulka","chapatti","wheat roti"], unit: "piece", kcal: 89,  p: 2.6, c: 17, f: 1.1, fb: 2.5 },
  { id: 2,  name: "Paratha (Plain)",       aliases: ["paratha","plain paratha","tawa paratha","sada paratha"], unit: "piece", kcal: 155, p: 3.5, c: 26, f: 4.5, fb: 3 },
  { id: 3,  name: "Paratha (Stuffed)",     aliases: ["aloo paratha","gobi paratha","stuffed paratha","mixed paratha","paneer paratha"], unit: "piece", kcal: 260, p: 5.5, c: 38, f: 10, fb: 4 },
  { id: 4,  name: "Puri",                  aliases: ["puri","poori","puri bhaji"], unit: "piece", kcal: 110, p: 2, c: 13, f: 5.5, fb: 1 },
  { id: 5,  name: "Naan",                  aliases: ["naan","naan bread","tandoori naan","butter naan"], unit: "piece", kcal: 262, p: 8.7, c: 45, f: 5.1, fb: 2 },
  { id: 6,  name: "Bhatura",               aliases: ["bhatura","batura"], unit: "piece", kcal: 300, p: 7, c: 42, f: 12, fb: 2 },
  { id: 7,  name: "Rice (Cooked)",         aliases: ["rice","chawal","boiled rice","plain rice","steamed rice","white rice"], unit: "cup", kcal: 195, p: 4, c: 43, f: 0.4, fb: 0.6, rawFactor: 2.8 },
  { id: 8,  name: "Biryani (Chicken)",     aliases: ["chicken biryani","biryani","murgh biryani","dum biryani"], unit: "plate", kcal: 450, p: 25, c: 55, f: 12, fb: 3 },
  { id: 9,  name: "Biryani (Veg)",         aliases: ["veg biryani","vegetable biryani","paneer biryani"], unit: "plate", kcal: 350, p: 10, c: 60, f: 8, fb: 4 },
  { id: 10, name: "Fried Rice",            aliases: ["fried rice","veg fried rice","egg fried rice","chinese rice"], unit: "plate", kcal: 320, p: 8, c: 52, f: 9, fb: 2 },
  { id: 11, name: "Upma",                  aliases: ["upma","rava upma","sooji upma"], unit: "bowl", kcal: 180, p: 4.5, c: 30, f: 5, fb: 2.5 },
  { id: 12, name: "Poha",                  aliases: ["poha","aval","beaten rice","pohaa","pohe"], unit: "bowl", kcal: 165, p: 4, c: 32, f: 3, fb: 1.5 },
  { id: 13, name: "Idli",                  aliases: ["idli","idly","steam idli"], unit: "piece", kcal: 58, p: 2, c: 12, f: 0.4, fb: 0.8 },
  { id: 14, name: "Dosa",                  aliases: ["dosa","plain dosa","sada dosa","dosai"], unit: "piece", kcal: 120, p: 3, c: 20, f: 3.5, fb: 1 },
  { id: 15, name: "Masala Dosa",           aliases: ["masala dosa","potato dosa","masala dosai"], unit: "piece", kcal: 220, p: 5, c: 36, f: 7, fb: 3 },
  { id: 16, name: "Sambar",                aliases: ["sambar","sambhar","south indian dal"], unit: "bowl", kcal: 80, p: 5, c: 12, f: 1.5, fb: 3 },
  { id: 17, name: "Dal Tadka",             aliases: ["dal","daal","yellow dal","tadka dal","toor dal","arhar dal","dal fry","dal tadka"], unit: "bowl", kcal: 180, p: 10, c: 28, f: 4, fb: 5, rawFactor: 2.8 },
  { id: 18, name: "Dal Makhani",           aliases: ["dal makhani","makhani dal","kali dal","black dal","black lentil dal","urad dal"], unit: "bowl", kcal: 280, p: 12, c: 30, f: 12, fb: 6 },
  { id: 19, name: "Chole",                 aliases: ["chole","chana masala","chickpea curry","chhole","kabuli chana"], unit: "bowl", kcal: 270, p: 13, c: 40, f: 8, fb: 9 },
  { id: 20, name: "Rajma",                 aliases: ["rajma","kidney beans curry","rajma curry","red kidney beans"], unit: "bowl", kcal: 260, p: 14, c: 38, f: 6, fb: 8 },
  { id: 21, name: "Paneer Butter Masala",  aliases: ["paneer butter masala","paneer makhani","butter paneer","pbm"], unit: "bowl", kcal: 350, p: 18, c: 20, f: 22, fb: 3 },
  { id: 22, name: "Paneer Tikka Masala",   aliases: ["paneer tikka masala","paneer tikka curry"], unit: "bowl", kcal: 320, p: 20, c: 18, f: 20, fb: 3 },
  { id: 23, name: "Butter Chicken",        aliases: ["butter chicken","murgh makhani","chicken makhani","bc"], unit: "bowl", kcal: 320, p: 24, c: 12, f: 20, fb: 1 },
  { id: 24, name: "Chicken Curry",         aliases: ["chicken curry","chicken masala","murgh curry","desi chicken"], unit: "bowl", kcal: 280, p: 26, c: 8, f: 16, fb: 1.5 },
  { id: 25, name: "Egg Curry",             aliases: ["egg curry","anda curry","anda masala"], unit: "bowl", kcal: 220, p: 14, c: 8, f: 15, fb: 1.5 },
  { id: 26, name: "Fish Curry",            aliases: ["fish curry","machli curry","fish masala","meen curry"], unit: "bowl", kcal: 200, p: 22, c: 5, f: 10, fb: 1 },
  { id: 27, name: "Palak Paneer",          aliases: ["palak paneer","spinach paneer","saag paneer"], unit: "bowl", kcal: 250, p: 14, c: 12, f: 17, fb: 4 },
  { id: 28, name: "Aloo Sabzi",            aliases: ["aloo sabzi","potato curry","aloo ki sabzi","batata bhaji"], unit: "bowl", kcal: 180, p: 4, c: 28, f: 6, fb: 3 },
  { id: 29, name: "Mixed Veg Sabzi",       aliases: ["veg sabzi","mixed sabzi","sabzi","mixed vegetables","mix veg"], unit: "bowl", kcal: 120, p: 4, c: 16, f: 5, fb: 4 },
  { id: 30, name: "Pav Bhaji",             aliases: ["pav bhaji","pavbhaji","pao bhaji"], unit: "serving", kcal: 420, p: 10, c: 60, f: 16, fb: 6 },
  { id: 31, name: "Chai (with milk)",      aliases: ["chai","tea","masala chai","adrak chai","cutting chai","ginger tea","milk tea"], unit: "cup", kcal: 60, p: 2, c: 8, f: 2, fb: 0 },
  { id: 32, name: "Lassi (Sweet)",         aliases: ["lassi","sweet lassi","mango lassi","dahi lassi"], unit: "glass", kcal: 180, p: 6, c: 30, f: 4, fb: 0.2 },
  { id: 33, name: "Buttermilk",            aliases: ["chaas","buttermilk","masala chaas","mattha"], unit: "glass", kcal: 40, p: 3, c: 5, f: 0.5, fb: 0 },
  { id: 34, name: "Milk (Full Fat)",       aliases: ["milk","doodh","full fat milk","full cream milk","whole milk"], unit: "cup", kcal: 150, p: 8, c: 12, f: 8, fb: 0 },
  { id: 35, name: "Curd / Dahi",           aliases: ["dahi","curd","yoghurt","yogurt","plain dahi"], unit: "katori", kcal: 60, p: 3.5, c: 4.5, f: 3, fb: 0 },
  { id: 36, name: "Raita",                 aliases: ["raita","boondi raita","cucumber raita","dahi raita"], unit: "katori", kcal: 65, p: 3, c: 8, f: 2, fb: 0.5 },
  { id: 37, name: "Samosa",                aliases: ["samosa","samosa chaat","aloo samosa"], unit: "piece", kcal: 130, p: 2.5, c: 16, f: 6.5, fb: 2 },
  { id: 38, name: "Vada Pav",              aliases: ["vada pav","vada pao","batata vada pav"], unit: "piece", kcal: 290, p: 6, c: 42, f: 11, fb: 3 },
  { id: 39, name: "Dhokla",                aliases: ["dhokla","khaman dhokla","besan dhokla"], unit: "piece", kcal: 80, p: 4, c: 12, f: 1.5, fb: 1.5 },
  { id: 40, name: "Jalebi",                aliases: ["jalebi","jalebi fafda"], unit: "piece", kcal: 75, p: 0.8, c: 17, f: 1.5, fb: 0 },
  { id: 41, name: "Gulab Jamun",           aliases: ["gulab jamun","gulab jamun mithai"], unit: "piece", kcal: 150, p: 2, c: 27, f: 5, fb: 0 },
  { id: 42, name: "Halwa",                 aliases: ["halwa","sooji halwa","atta halwa","moong dal halwa"], unit: "katori", kcal: 250, p: 4, c: 36, f: 10, fb: 1 },
  { id: 43, name: "Egg (Boiled)",          aliases: ["boiled egg","anda","egg","hard boiled egg","soft boiled egg"], unit: "piece", kcal: 70, p: 6, c: 0.5, f: 5, fb: 0 },
  { id: 44, name: "Omelette",              aliases: ["omelette","egg omelette","masala omelette","anda omelette","omlette","omelet"], unit: "egg", kcal: 90, p: 6.5, c: 0.5, f: 7, fb: 0, g: 55 },
  { id: 45, name: "Khichdi",               aliases: ["khichdi","dal khichdi","masala khichdi","moong khichdi"], unit: "bowl", kcal: 200, p: 8, c: 34, f: 4, fb: 4 },
  { id: 46, name: "Pongal",                aliases: ["pongal","ven pongal","khara pongal","rice pongal"], unit: "bowl", kcal: 220, p: 6, c: 38, f: 5, fb: 2 },
  { id: 47, name: "Curd Rice",             aliases: ["curd rice","dahi chawal","thayir sadam","mosaranna"], unit: "bowl", kcal: 180, p: 6, c: 30, f: 4, fb: 1 },
  { id: 48, name: "Ghee",                  aliases: ["ghee","desi ghee"], unit: "tsp", kcal: 45, p: 0, c: 0, f: 5, fb: 0, modifier: true },
  { id: 49, name: "Butter",                aliases: ["butter","amul butter","white butter","makhan","salted butter"], unit: "tsp", kcal: 36, p: 0, c: 0, f: 4, fb: 0, modifier: true },
  { id: 50, name: "Oil",                   aliases: ["oil","cooking oil","refined oil","sarson ka tel","mustard oil"], unit: "tsp", kcal: 45, p: 0, c: 0, f: 5, fb: 0, modifier: true },
  { id: 51, name: "Banana",                aliases: ["banana","kela","plantain"], unit: "medium", kcal: 105, p: 1.3, c: 27, f: 0.3, fb: 3 },
  { id: 52, name: "Apple",                 aliases: ["apple","seb"], unit: "medium", kcal: 78, p: 0.4, c: 21, f: 0.2, fb: 3.5 },
  { id: 53, name: "Orange",                aliases: ["orange","santra","mosambi","sweet lime"], unit: "medium", kcal: 62, p: 1.2, c: 15, f: 0.2, fb: 3 },
  { id: 54, name: "Mixed Fruit",           aliases: ["fruit salad","mixed fruit","fruits"], unit: "bowl", kcal: 80, p: 1, c: 19, f: 0.3, fb: 3 },
  { id: 55, name: "Sprouts",               aliases: ["sprouts","moong sprouts","mixed sprouts","germinated moong"], unit: "bowl", kcal: 85, p: 7, c: 14, f: 0.5, fb: 5 },
  { id: 56, name: "Peanuts",               aliases: ["peanuts","moongfali","groundnuts","roasted peanuts"], unit: "handful", kcal: 170, p: 7.5, c: 5, f: 14, fb: 2.5 },
  { id: 57, name: "Almonds",               aliases: ["almonds","badam","soaked almonds","almond nuts"], unit: "piece", kcal: 7, p: 0.3, c: 0.2, f: 0.6, fb: 0.1 },
  { id: 58, name: "Protein Shake",         aliases: ["protein shake","whey shake","protein smoothie","gym shake"], unit: "scoop", kcal: 120, p: 24, c: 3, f: 2, fb: 1 },
  { id: 59, name: "Bhel Puri",             aliases: ["bhel","bhelpuri","bhel puri","churmuri"], unit: "plate", kcal: 290, p: 6, c: 48, f: 8, fb: 4 },
  { id: 60, name: "Pani Puri",             aliases: ["pani puri","panipuri","golgappa","gol gappa","puchka","gupchup"], unit: "plate", kcal: 180, p: 3, c: 32, f: 5, fb: 2 },
  { id: 61, name: "Sev Puri",              aliases: ["sev puri","sevpuri","sev puri chaat"], unit: "plate", kcal: 320, p: 5, c: 42, f: 14, fb: 3 },
  { id: 62, name: "Dahi Puri",             aliases: ["dahi puri","dahipuri","dahi puri chaat"], unit: "plate", kcal: 280, p: 6, c: 38, f: 11, fb: 3 },
  { id: 63, name: "Papad",                 aliases: ["papad","papadum","appalam","roasted papad","fried papad"], unit: "piece", kcal: 50, p: 1.5, c: 7, f: 1.5, fb: 1 },
  { id: 64, name: "Biscuit",               aliases: ["biscuit","biscuits","marie biscuit","parle g","glucose biscuit","cookies"], unit: "piece", kcal: 40, p: 0.7, c: 6, f: 1.5, fb: 0.3 },
  { id: 65, name: "Rasam",                 aliases: ["rasam","charu","saaru","tomato rasam","pepper rasam"], unit: "bowl", kcal: 100, p: 3, c: 18, f: 2, fb: 1 },
  { id: 66, name: "Kadhi",                 aliases: ["kadhi","besan kadhi","kadhi pakoda","punjabi kadhi","gujarati kadhi"], unit: "bowl", kcal: 180, p: 6, c: 14, f: 11, fb: 1 },
  { id: 67, name: "Chole Bhature",         aliases: ["chole bhature","chole bhatura","chana bhatura","chole bhature plate"], unit: "plate", kcal: 650, p: 16, c: 80, f: 28, fb: 9 },
  { id: 68, name: "Chicken Breast",        aliases: ["chicken breast","grilled chicken","boiled chicken","tandoori chicken breast","skinless chicken","chicken breast piece"], unit: "100g", kcal: 165, p: 31, c: 0, f: 3.6, fb: 0, rawFactor: 0.73 },
  { id: 69, name: "Paneer (Raw/Grilled)",  aliases: ["paneer","raw paneer","grilled paneer","tandoori paneer","paneer cubes"], unit: "100g", kcal: 265, p: 18, c: 4, f: 20, fb: 0 },
  { id: 70, name: "Tofu",                  aliases: ["tofu","soya paneer","bean curd"], unit: "100g", kcal: 145, p: 15, c: 3, f: 8, fb: 1 },
  { id: 71, name: "Egg Whites",            aliases: ["egg white","egg whites","boiled egg whites","anda safedi"], unit: "white", kcal: 17, p: 3.6, c: 0.2, f: 0.1, fb: 0 },
  { id: 72, name: "Bread (slice)",         aliases: ["bread","bread slice","white bread","brown bread","toast","slice of bread","atta bread","wheat bread","whole wheat bread","multigrain bread"], unit: "slice", kcal: 75, p: 3, c: 14, f: 1, fb: 1 },
  { id: 73, name: "Honey",                 aliases: ["honey","shahad","madh"], unit: "tbsp", kcal: 64, p: 0, c: 17, f: 0, fb: 0 },
  { id: 74, name: "Jam",                   aliases: ["jam","mixed fruit jam","strawberry jam","marmalade"], unit: "tbsp", kcal: 56, p: 0, c: 14, f: 0, fb: 0.3 },
  { id: 75, name: "Sugar",                 aliases: ["sugar","cheeni","chini","white sugar"], unit: "tsp", kcal: 16, p: 0, c: 4, f: 0, fb: 0 },
  { id: 76, name: "Lemon Rice",            aliases: ["lemon rice","chitranna","nimmakaya annam"], unit: "bowl", kcal: 250, p: 4, c: 45, f: 7, fb: 2 },
  { id: 77, name: "Mango",                 aliases: ["mango","aam","mangoes","alphonso"], unit: "medium", kcal: 150, p: 1.4, c: 38, f: 0.6, fb: 2.6 },
  { id: 78, name: "Guava",                 aliases: ["guava","amrud","peru"], unit: "medium", kcal: 68, p: 2.6, c: 14, f: 1, fb: 5.4 },
  { id: 79, name: "Papaya",                aliases: ["papaya","papita"], unit: "bowl", kcal: 60, p: 0.7, c: 15, f: 0.2, fb: 2.5 },
  { id: 80, name: "Watermelon",            aliases: ["watermelon","tarbooz","tarbuj"], unit: "bowl", kcal: 46, p: 0.9, c: 11, f: 0.2, fb: 0.6 },
  { id: 81, name: "Grapes",                aliases: ["grapes","angoor","angur"], unit: "bowl", kcal: 70, p: 0.7, c: 18, f: 0.2, fb: 0.9 },
  { id: 82, name: "Pomegranate",           aliases: ["pomegranate","anaar","anar"], unit: "bowl", kcal: 100, p: 2, c: 22, f: 1, fb: 4 },
  { id: 83, name: "Chikoo",                aliases: ["chikoo","sapota","sapodilla","chiku"], unit: "medium", kcal: 83, p: 0.4, c: 20, f: 1, fb: 5.6 },
  { id: 84, name: "Pineapple",             aliases: ["pineapple","ananas"], unit: "bowl", kcal: 74, p: 0.8, c: 19, f: 0.2, fb: 2.3 },
  { id: 85, name: "Custard Apple",         aliases: ["custard apple","sitaphal","sharifa"], unit: "medium", kcal: 100, p: 2, c: 24, f: 0.3, fb: 4.4 },
  { id: 86, name: "Cucumber",              aliases: ["cucumber","kheera","kakdi","kakri"], unit: "bowl", kcal: 16, p: 0.7, c: 4, f: 0.1, fb: 0.5 },
  { id: 87, name: "Carrot",                aliases: ["carrot","gajar"], unit: "medium", kcal: 25, p: 0.6, c: 6, f: 0.1, fb: 1.7 },
  { id: 88, name: "Tomato",                aliases: ["tomato","tamatar"], unit: "medium", kcal: 22, p: 1, c: 5, f: 0.2, fb: 1.2 },
  { id: 89, name: "Green Salad",           aliases: ["green salad","salad","kachumber","veg salad"], unit: "plate", kcal: 40, p: 2, c: 8, f: 0.5, fb: 3 },
  { id: 90, name: "Chicken Tikka",         aliases: ["chicken tikka","tandoori chicken","chicken tikka dry","murgh tikka"], unit: "piece", kcal: 55, p: 9, c: 1, f: 2, fb: 0 },
  { id: 91, name: "Paneer Tikka (dry)",    aliases: ["paneer tikka","paneer tikka dry","grilled paneer tikka"], unit: "piece", kcal: 70, p: 4, c: 2, f: 5, fb: 0.3 },
  { id: 92, name: "Roasted Chana",         aliases: ["roasted chana","bhuna chana","roasted chickpeas","chana snack","phutana"], unit: "handful", kcal: 120, p: 7, c: 20, f: 2, fb: 5 },
  { id: 93, name: "Uttapam",               aliases: ["uttapam","uthappam","rava uttapam","onion uttapam"], unit: "piece", kcal: 175, p: 4, c: 25, f: 6, fb: 2 },
  { id: 94, name: "Maggi",                 aliases: ["maggi","maggie","masala noodles","instant noodles","2 minute noodles"], unit: "pack", kcal: 350, p: 8, c: 50, f: 13, fb: 2 },
  { id: 95, name: "Pizza (slice)",         aliases: ["pizza","pizza slice","cheese pizza","veg pizza","margherita"], unit: "slice", kcal: 285, p: 12, c: 36, f: 10, fb: 2 },
  { id: 96, name: "Ice Cream",             aliases: ["ice cream","icecream","vanilla ice cream","scoop of ice cream"], unit: "scoop", kcal: 140, p: 2.5, c: 16, f: 7, fb: 0.5 },
  { id: 97, name: "Matar Paneer",          aliases: ["matar paneer","mutter paneer","peas paneer","paneer matar"], unit: "bowl", kcal: 280, p: 14, c: 18, f: 16, fb: 4 },
  { id: 98, name: "Oats (Plain)",          aliases: ["oats","oatmeal","oats bowl","masala oats","overnight oats","quaker oats","quaker","rolled oats","plain oats"], unit: "bowl", kcal: 150, p: 5, c: 27, f: 3, fb: 4, g: 40 },
  { id: 99, name: "Peanut Butter",         aliases: ["peanut butter","pb","moongfali butter"], unit: "tbsp", kcal: 95, p: 4, c: 3, f: 8, fb: 1.5 },
  { id: 100, name: "Soya Chunks",          aliases: ["soya chunks","soya nuggets","nutrela","meal maker","soya","soyabean chunks"], unit: "bowl", kcal: 170, p: 26, c: 18, f: 1.5, fb: 6, g: 50 },
  { id: 101, name: "Sweet Potato",         aliases: ["sweet potato","shakarkandi","shakarkand"], unit: "medium", kcal: 115, p: 2, c: 27, f: 0.2, fb: 4 },
  { id: 102, name: "Brown Rice",           aliases: ["brown rice","brown chawal"], unit: "cup", kcal: 215, p: 5, c: 45, f: 1.8, fb: 3.5, rawFactor: 2.6 },
  { id: 103, name: "Greek Yogurt",         aliases: ["greek yogurt","hung curd","hung yogurt","chakka","greek yoghurt"], unit: "cup", kcal: 100, p: 10, c: 6, f: 0.5, fb: 0 },
  { id: 104, name: "Quinoa",               aliases: ["quinoa","quinoa bowl"], unit: "bowl", kcal: 220, p: 8, c: 39, f: 4, fb: 5 },
  { id: 105, name: "Protein Bar",          aliases: ["protein bar","energy bar","yogabar","protein cookie"], unit: "bar", kcal: 200, p: 20, c: 22, f: 7, fb: 3 },
  { id: 106, name: "Grilled Fish",         aliases: ["grilled fish","fish fillet","basa","tilapia","fish tikka","grilled fish fillet"], unit: "fillet", kcal: 180, p: 30, c: 1, f: 6, fb: 0 },
  { id: 107, name: "Low-Fat Paneer",       aliases: ["low fat paneer","low-fat paneer","diet paneer","toned paneer","skimmed paneer","low fat cottage cheese"], unit: "100g", kcal: 160, p: 20, c: 5, f: 7, fb: 0 },
  { id: 108, name: "Low-Fat Milk",         aliases: ["toned milk","skimmed milk","skim milk","double toned milk","low fat milk","low-fat milk"], unit: "cup", kcal: 100, p: 8, c: 12, f: 2.5, fb: 0 },
  { id: 109, name: "Low-Fat Curd",         aliases: ["low fat curd","low-fat curd","low fat dahi","low fat yogurt","greek yogurt low fat","skimmed curd"], unit: "katori", kcal: 45, p: 4, c: 5, f: 1, fb: 0 },
  { id: 110, name: "High-Protein Peanut Butter", aliases: ["high protein peanut butter","hp peanut butter","protein peanut butter","pintola high protein","myfitness peanut butter"], unit: "tbsp", kcal: 88, p: 5, c: 3, f: 6, fb: 1 },
  { id: 111, name: "High-Protein Roti",    aliases: ["high protein roti","protein roti","high protein atta roti","multigrain protein roti"], unit: "piece", kcal: 100, p: 5, c: 15, f: 2, fb: 3 },
  { id: 112, name: "High-Protein Bread",   aliases: ["high protein bread","protein bread"], unit: "slice", kcal: 80, p: 6, c: 12, f: 1.5, fb: 2 },
  { id: 113, name: "Protein Chips",        aliases: ["protein chips","protein puffs","roasted protein chips","open secret"], unit: "pack", kcal: 120, p: 10, c: 12, f: 4, fb: 2 },
  { id: 114, name: "Protein Muesli",       aliases: ["protein muesli","high protein muesli","protein granola"], unit: "bowl", kcal: 200, p: 14, c: 28, f: 5, fb: 5 },
  { id: 115, name: "Creatine",             aliases: ["creatine","creatine monohydrate","creatine scoop"], unit: "scoop", kcal: 0, p: 0, c: 0, f: 0, fb: 0 },
  { id: 116, name: "BCAA / EAA",           aliases: ["bcaa","eaa","amino acids","intra workout drink"], unit: "scoop", kcal: 10, p: 0, c: 2, f: 0, fb: 0 },
  { id: 117, name: "Black Coffee",         aliases: ["black coffee","americano","espresso","kali coffee","black coffee without sugar"], unit: "cup", kcal: 5, p: 0.3, c: 0, f: 0, fb: 0 },
  { id: 118, name: "Green Tea",            aliases: ["green tea","green chai","matcha","lemon green tea"], unit: "cup", kcal: 2, p: 0, c: 0.5, f: 0, fb: 0 },
  { id: 119, name: "Chia Seeds",           aliases: ["chia seeds","chia","chiaseeds","chia seed"], unit: "tbsp", kcal: 58, p: 2, c: 5, f: 3.7, fb: 4, g: 12 },
  { id: 120, name: "Flax Seeds",           aliases: ["flax seeds","flaxseed","alsi","alsi seeds","linseed"], unit: "tbsp", kcal: 55, p: 1.9, c: 3, f: 4.3, fb: 2.8, g: 10 },
  { id: 121, name: "Pumpkin Seeds",        aliases: ["pumpkin seeds","pepitas","kaddu ke beej"], unit: "tbsp", kcal: 56, p: 3, c: 1, f: 4.9, fb: 0.6, g: 10 },
  { id: 122, name: "Dates",                aliases: ["dates","khajur","date","medjool dates","khajoor"], unit: "piece", kcal: 66, p: 0.4, c: 18, f: 0, fb: 1.6, g: 24 },
  { id: 123, name: "Bhakri (Jowar/Bajra)", aliases: ["bhakri","jowar bhakri","jawar bhakri","bajra bhakri","multigrain bhakri","bhakhri","jowar roti","bajra roti"], unit: "piece", kcal: 120, p: 3, c: 25, f: 1, fb: 3 },
  { id: 124, name: "Paneer Bhurji",        aliases: ["paneer bhurji","paneer burji","scrambled paneer","paneer bhurjee"], unit: "bowl", kcal: 300, p: 15, c: 8, f: 23, fb: 1.5 },
  { id: 125, name: "Sattu Drink",          aliases: ["sattu drink","sattu","sattu shake","sattu sharbat","sattu water"], unit: "glass", kcal: 110, p: 6.5, c: 16, f: 1.5, fb: 3 },
  { id: 126, name: "Mutton Biryani",       aliases: ["mutton biryani","mutton biriyani","gosht biryani","lamb biryani"], unit: "plate", kcal: 400, p: 16, c: 42, f: 17, fb: 2.5, g: 250 },
  { id: 127, name: "Broccoli",             aliases: ["broccoli","steamed broccoli","boiled broccoli"], unit: "cup", kcal: 31, p: 2.5, c: 6, f: 0.3, fb: 2.4, g: 90 },
  { id: 128, name: "Potato (Boiled)",      aliases: ["potato","boiled potato","aloo boiled","uble aloo","boiled aloo"], unit: "medium", kcal: 115, p: 2.5, c: 26, f: 0.1, fb: 2.4, g: 150 },
  { id: 129, name: "Muskmelon",            aliases: ["muskmelon","kharbuja","cantaloupe","melon"], unit: "cup", kcal: 53, p: 1.3, c: 13, f: 0.3, fb: 1.4, g: 150 },
  { id: 130, name: "Clear Whey",           aliases: ["clear whey","clear whey protein","clear protein","juicy whey"], unit: "scoop", kcal: 85, p: 20, c: 1, f: 0.2, fb: 0, g: 30 },
  { id: 131, name: "Honey Chilli Potato",  aliases: ["honey chilli potato","honey chili potato","chilli potato"], unit: "plate", kcal: 350, p: 4, c: 45, f: 18, fb: 3 },
  { id: 132, name: "Coffee (with milk)",   aliases: ["coffee","milk coffee","filter coffee","instant coffee","nescafe","coffee with milk"], unit: "cup", kcal: 90, p: 2.5, c: 12, f: 3, fb: 0 },
  { id: 133, name: "Egg (Fried/Half Fry)", aliases: ["fried egg","half fry","egg half fry","half fried egg","anda fry","egg fry","sunny side up","bullseye egg"], unit: "piece", kcal: 90, p: 6.3, c: 0.4, f: 7, fb: 0 },
  { id: 134, name: "High-Protein Oats",    aliases: ["high protein oats","protein oats","yogabar oats","yoga bar oats","whey oats","protein oatmeal"], unit: "bowl", kcal: 145, p: 10.5, c: 22, f: 3.5, fb: 4, g: 40 },
  { id: 135, name: "Diet Cola",            aliases: ["diet coke","coke zero","diet pepsi","zero coke","diet cola","zero sugar cold drink"], unit: "can", kcal: 1, p: 0, c: 0, f: 0, fb: 0, g: 330 },
  { id: 136, name: "Cold Drink (Cola)",    aliases: ["coke","coca cola","thums up","pepsi","sprite","cold drink","soft drink","limca","fanta","mountain dew"], unit: "can", kcal: 140, p: 0, c: 35, f: 0, fb: 0, g: 330 },
  { id: 137, name: "Coconut Water",        aliases: ["coconut water","nariyal pani","daab water","tender coconut water"], unit: "glass", kcal: 40, p: 0.5, c: 9, f: 0, fb: 0, g: 200 },
  { id: 138, name: "Sauf / Jeera Water",   aliases: ["sauf water","saunf water","jeera water","fennel water","cumin water"], unit: "glass", kcal: 5, p: 0, c: 1, f: 0, fb: 0 },
  { id: 139, name: "Nimbu Pani (Sweet)",   aliases: ["nimbu pani","shikanji","lemon water with sugar","lemonade","sweet lime water"], unit: "glass", kcal: 60, p: 0, c: 15, f: 0, fb: 0 },
  { id: 140, name: "Bread Pakoda",         aliases: ["bread pakoda","bread pakora","stuffed bread pakora"], unit: "piece", kcal: 230, p: 6, c: 27, f: 11, fb: 2 },
  { id: 141, name: "Thalipeeth",           aliases: ["thalipeeth","bhajni thalipeeth","methi thalipeeth"], unit: "piece", kcal: 130, p: 4, c: 20, f: 4, fb: 3 },
  { id: 142, name: "Fafda",                aliases: ["fafda","fafda gathiya","phaphda"], unit: "piece", kcal: 45, p: 1, c: 5, f: 2.4, fb: 0.5 },
  { id: 143, name: "Gatte ki Sabzi",       aliases: ["gatte ki sabzi","gatta curry","gatte curry","besan gatta sabzi","gatte ki kadhi"], unit: "bowl", kcal: 250, p: 8, c: 25, f: 13, fb: 3 },
  { id: 144, name: "Dal Dhokli",           aliases: ["dal dhokli","daal dhokli","varan phal"], unit: "bowl", kcal: 300, p: 11, c: 45, f: 8, fb: 6 },
  { id: 145, name: "Aamras",               aliases: ["aamras","aam ras","mango pulp","amras"], unit: "katori", kcal: 150, p: 1, c: 35, f: 1, fb: 2, g: 150 },
  { id: 146, name: "Achar / Pickle",       aliases: ["achar","pickle","aam ka achar","mango pickle","lemon pickle","mixed pickle"], unit: "tbsp", kcal: 30, p: 0.3, c: 3, f: 2, fb: 0.5 },
  { id: 147, name: "Papad",                aliases: ["papad","papadum","urad papad","roasted papad","urad dal papad","masala papad"], unit: "piece", kcal: 45, p: 2, c: 6, f: 1.5, fb: 0.5 },
  { id: 148, name: "Rasgulla",             aliases: ["rasgulla","rosogolla","rasgula","sponge rasgulla"], unit: "piece", kcal: 120, p: 2, c: 25, f: 1.5, fb: 0 },
  { id: 149, name: "Vada (Medu/Batata)",   aliases: ["vada","wada","medu vada","batata vada","aloo vada","urad vada"], unit: "piece", kcal: 140, p: 3, c: 15, f: 7, fb: 1.5 },
  { id: 150, name: "Egg Bhurji",           aliases: ["egg bhurji","anda bhurji","bhurji","egg bhurji pav","scrambled eggs"], unit: "egg", kcal: 100, p: 6.5, c: 2, f: 7.5, fb: 0.3 },
  { id: 151, name: "Almonds",              aliases: ["almond","almonds","badam","soaked almonds","roasted almonds"], unit: "piece", kcal: 7, p: 0.26, c: 0.24, f: 0.6, fb: 0.15, g: 1.2 },
  { id: 152, name: "Cashews",              aliases: ["cashew","cashews","kaju","roasted cashew","salted cashews","cashew nuts"], unit: "piece", kcal: 9, p: 0.3, c: 0.5, f: 0.7, fb: 0.05, g: 1.7 },
  { id: 153, name: "Walnut",               aliases: ["walnut","walnuts","akhrot","walnut half"], unit: "half", kcal: 13, p: 0.3, c: 0.3, f: 1.3, fb: 0.13, g: 2 },
  { id: 154, name: "Pistachios",           aliases: ["pistachio","pistachios","pista","salted pista"], unit: "piece", kcal: 4, p: 0.15, c: 0.2, f: 0.32, fb: 0.07, g: 0.7 },
  { id: 155, name: "Raisins",              aliases: ["raisins","kishmish","raisin","black raisins","munakka"], unit: "tbsp", kcal: 30, p: 0.3, c: 8, f: 0, fb: 0.4, g: 10 },
  { id: 156, name: "Anjeer (Dried Fig)",   aliases: ["anjeer","dried fig","dry fig","figs dried","dried anjeer"], unit: "piece", kcal: 20, p: 0.3, c: 5, f: 0.1, fb: 1, g: 8 },
  { id: 157, name: "Dried Apricot",        aliases: ["dried apricot","khubani","apricot dry","jardalu"], unit: "piece", kcal: 19, p: 0.3, c: 5, f: 0, fb: 0.6, g: 8 },
  { id: 158, name: "Makhana (Roasted)",    aliases: ["makhana","fox nuts","foxnuts","roasted makhana","phool makhana","lotus seeds"], unit: "bowl", kcal: 87, p: 2.4, c: 19, f: 0.3, fb: 3.5, g: 25 },
  { id: 159, name: "Peanuts (Roasted)",    aliases: ["peanuts","roasted peanuts","moongfali","groundnuts","salted peanuts","boiled peanuts"], unit: "handful", kcal: 170, p: 7.5, c: 5, f: 14.5, fb: 2.5, g: 30 },
  { id: 160, name: "Dry Coconut (Copra)",  aliases: ["dry coconut","copra","sukha nariyal","coconut slice dry","desiccated coconut"], unit: "piece", kcal: 99, p: 1, c: 3.7, f: 9.9, fb: 2.4, g: 15 },
  { id: 161, name: "Mixed Dry Fruits",     aliases: ["mixed dry fruits","dry fruits","mixed nuts","trail mix","dry fruit mix"], unit: "handful", kcal: 165, p: 4.5, c: 11, f: 12, fb: 2, g: 30 },
  { id: 162, name: "Prunes",               aliases: ["prunes","prune","dried plum","sukha aloo bukhara"], unit: "piece", kcal: 23, p: 0.2, c: 6, f: 0, fb: 0.7, g: 9.5 },
  { id: 163, name: "Sunflower Seeds",      aliases: ["sunflower seeds","surajmukhi seeds","sunflower seed"], unit: "tbsp", kcal: 58, p: 2.1, c: 2, f: 5.2, fb: 0.9, g: 10 },
  { id: 164, name: "Melon Seeds (Magaj)",  aliases: ["melon seeds","magaj","watermelon seeds","char magaj"], unit: "tbsp", kcal: 56, p: 2.8, c: 1, f: 4.7, fb: 0.5, g: 10 },
  { id: 165, name: "Dried Cranberries",    aliases: ["dried cranberries","cranberries","craisins"], unit: "tbsp", kcal: 32, p: 0.1, c: 8.2, f: 0.1, fb: 0.5, g: 10 },
  { id: 166, name: "Kaju Katli",           aliases: ["kaju katli","kaju barfi","cashew barfi","kaju katri"], unit: "piece", kcal: 60, p: 1, c: 7, f: 3.2, fb: 0.2, g: 15 },
  { id: 167, name: "Besan Ladoo",          aliases: ["besan ladoo","besan laddu","besan laddoo"], unit: "piece", kcal: 165, p: 3.5, c: 18, f: 9, fb: 1, g: 35 },
  { id: 168, name: "Motichoor Ladoo",      aliases: ["motichoor ladoo","boondi ladoo","motichur laddu","ladoo","laddu"], unit: "piece", kcal: 140, p: 2, c: 22, f: 5.5, fb: 0.5, g: 30 },
  { id: 169, name: "Rasmalai",             aliases: ["rasmalai","ras malai","rossomalai"], unit: "piece", kcal: 160, p: 5, c: 18, f: 7.5, fb: 0, g: 80 },
  { id: 170, name: "Milk Barfi",           aliases: ["barfi","burfi","milk barfi","khoya barfi","plain barfi","doodh barfi"], unit: "piece", kcal: 105, p: 2.5, c: 14, f: 4.5, fb: 0, g: 25 },
  { id: 171, name: "Peda",                 aliases: ["peda","pedha","milk peda","kesar peda","mathura peda"], unit: "piece", kcal: 110, p: 2.5, c: 15, f: 4.5, fb: 0, g: 25 },
  { id: 172, name: "Kheer",                aliases: ["kheer","rice kheer","payasam","payesh","seviyan kheer"], unit: "katori", kcal: 200, p: 5.5, c: 30, f: 7, fb: 0.3, g: 150 },
  { id: 173, name: "Gajar Halwa",          aliases: ["gajar halwa","gajar ka halwa","carrot halwa","gajrela"], unit: "katori", kcal: 250, p: 4, c: 30, f: 13, fb: 2.5, g: 120 },
  { id: 174, name: "Mysore Pak",           aliases: ["mysore pak","mysore pak sweet","mysurpa"], unit: "piece", kcal: 160, p: 1.5, c: 17, f: 10, fb: 0.3, g: 30 },
  { id: 175, name: "Soan Papdi",           aliases: ["soan papdi","son papdi","patisa","sohan papdi"], unit: "piece", kcal: 130, p: 1.5, c: 16, f: 7, fb: 0.3, g: 25 },
  { id: 176, name: "Sandesh",              aliases: ["sandesh","sondesh","bengali sandesh"], unit: "piece", kcal: 100, p: 3, c: 14, f: 3.5, fb: 0, g: 30 },
  { id: 177, name: "Chikki",               aliases: ["chikki","peanut chikki","til chikki","gud chikki","gajak"], unit: "piece", kcal: 100, p: 2, c: 13, f: 4.5, fb: 0.5, g: 20 },
  { id: 178, name: "Malpua",               aliases: ["malpua","malpuas","mal pua"], unit: "piece", kcal: 180, p: 2, c: 25, f: 8, fb: 0.3, g: 50 },
  { id: 179, name: "Modak (Steamed)",      aliases: ["modak","ukdiche modak","steamed modak","modak sweet"], unit: "piece", kcal: 110, p: 1.5, c: 18, f: 3.5, fb: 0.5, g: 40 },
  { id: 180, name: "Kulfi",                aliases: ["kulfi","malai kulfi","kesar kulfi","kulfi stick","matka kulfi"], unit: "stick", kcal: 150, p: 4, c: 17, f: 8, fb: 0, g: 70 },
  { id: 181, name: "Green Leafy Vegetables", aliases: ["green vegetable","green vegetables","green veg","hari sabzi","leafy vegetables","leafy greens","greens","palak","spinach","saag","methi leaves"], unit: "cup", kcal: 25, p: 3, c: 4, f: 0.3, fb: 2.5, g: 100 },
];

const FOOD_BY_ID = Object.fromEntries(FOODS.map(f => [f.id, f]));

module.exports = { FOODS, FOOD_BY_ID };
