// NutriDesi food database — Indian items with Hinglish aliases.
// Aliases are the single biggest lever on parse accuracy. Expand these over time.
// Fields: id, name, aliases[], unit, kcal, protein(p), carbs(c), fat(f), fibre(fb), grams(g)?, modifier?

const FOODS = [
  { id: 1,  name: "Roti / Chapati",       aliases: ["roti","chapati","phulka","chappati","fulka","chapatti","wheat roti"], unit: "piece", kcal: 89,  p: 2.6, c: 17, f: 1.1, fb: 2.5 },
  { id: 2,  name: "Paratha (Plain)",       aliases: ["paratha","plain paratha","tawa paratha","sada paratha"], unit: "piece", kcal: 155, p: 3.5, c: 26, f: 4.5, fb: 3 },
  { id: 3,  name: "Paratha (Stuffed)",     aliases: ["gobi paratha","stuffed paratha","mixed paratha","mooli paratha"], unit: "piece", kcal: 260, p: 5.5, c: 38, f: 10, fb: 4 },
  { id: 4,  name: "Puri",                  aliases: ["puri","poori","puri bhaji"], unit: "piece", kcal: 110, p: 2, c: 13, f: 5.5, fb: 1 },
  { id: 5,  name: "Naan",                  aliases: ["naan","naan bread","tandoori naan","butter naan"], unit: "piece", kcal: 262, p: 8.7, c: 45, f: 5.1, fb: 2 },
  { id: 6,  name: "Bhatura",               aliases: ["bhatura","batura"], unit: "piece", kcal: 300, p: 7, c: 42, f: 12, fb: 2 },
  { id: 7,  name: "Rice (Cooked)",         aliases: ["rice","chawal","boiled rice","plain rice","steamed rice","white rice"], unit: "cup", kcal: 195, p: 4, c: 43, f: 0.4, fb: 0.6, rawFactor: 2.8 },
  { id: 8,  name: "Biryani (Chicken)",     aliases: ["chicken biryani","murgh biryani","chicken dum biryani"], unit: "plate", kcal: 450, p: 25, c: 55, f: 12, fb: 3 },
  // Bare category words default to the VEG variant — non-veg needs an explicit
  // protein word ("chicken biryani"). Policy set 2026-07-19.
  { id: 9,  name: "Biryani (Veg)",         aliases: ["veg biryani","biryani","vegetable biryani","paneer biryani","dum biryani","biriyani","veg dum biryani"], unit: "plate", kcal: 350, p: 10, c: 60, f: 8, fb: 4 },
  { id: 10, name: "Fried Rice",            aliases: ["fried rice","veg fried rice","egg fried rice","chinese rice"], unit: "plate", kcal: 320, p: 8, c: 52, f: 9, fb: 2 },
  { id: 11, name: "Upma",                  aliases: ["upma","rava upma","sooji upma"], unit: "bowl", kcal: 180, p: 4.5, c: 30, f: 5, fb: 2.5 },
  { id: 12, name: "Poha",                  aliases: ["poha","aval","beaten rice","pohaa","pohe"], unit: "bowl", kcal: 165, p: 4, c: 32, f: 3, fb: 1.5 },
  { id: 13, name: "Idli",                  aliases: ["idli","idly","steam idli"], unit: "piece", kcal: 58, p: 2, c: 12, f: 0.4, fb: 0.8 },
  { id: 14, name: "Dosa",                  aliases: ["dosa","plain dosa","sada dosa","dosai"], unit: "piece", kcal: 120, p: 3, c: 20, f: 3.5, fb: 1 },
  { id: 15, name: "Masala Dosa",           aliases: ["masala dosa","potato dosa","masala dosai"], unit: "piece", kcal: 220, p: 5, c: 36, f: 7, fb: 3 },
  { id: 16, name: "Sambar",                aliases: ["sambar","sambhar","south indian dal"], unit: "bowl", kcal: 80, p: 5, c: 12, f: 1.5, fb: 3 },
  { id: 17, name: "Dal Tadka",             aliases: ["dal","daal","yellow dal","tadka dal","toor dal","arhar dal","dal fry","dal tadka"], unit: "bowl", kcal: 180, p: 10, c: 28, f: 4, fb: 5, rawFactor: 2.8 },
  { id: 18, name: "Dal Makhani",           aliases: ["dal makhani","makhani dal","kali dal","black dal","black lentil dal","urad dal"], unit: "bowl", kcal: 280, p: 12, c: 30, f: 12, fb: 6 },
  { id: 19, name: "Chole",                 aliases: ["chole","chana masala","chickpea curry","chhole","kabuli chana"], unit: "bowl", kcal: 270, p: 13, c: 40, f: 8, fb: 9 },
  { id: 20, name: "Rajma",                 aliases: ["rajma","kidney beans curry","rajma curry","red kidney beans"], unit: "bowl", kcal: 260, p: 14, c: 38, f: 6, fb: 8 },
  { id: 21, name: "Paneer Butter Masala",  aliases: ["paneer butter masala","paneer makhani","butter paneer","pbm"], unit: "bowl", kcal: 350, p: 18, c: 20, f: 22, fb: 3 },
  { id: 22, name: "Paneer Tikka Masala",   aliases: ["paneer tikka masala","paneer tikka curry"], unit: "bowl", kcal: 320, p: 20, c: 18, f: 20, fb: 3 },
  { id: 23, name: "Butter Chicken",        aliases: ["butter chicken","murgh makhani","chicken makhani","bc"], unit: "bowl", kcal: 320, p: 24, c: 12, f: 20, fb: 1 },
  { id: 24, name: "Chicken Curry",         aliases: ["chicken curry","chicken masala","murgh curry","desi chicken"], unit: "bowl", kcal: 280, p: 26, c: 8, f: 16, fb: 1.5 },
  { id: 25, name: "Egg Curry",             aliases: ["egg curry","anda curry","anda masala"], unit: "bowl", kcal: 220, p: 14, c: 8, f: 15, fb: 1.5 },
  { id: 26, name: "Fish Curry",            aliases: ["fish curry","machli curry","fish masala","meen curry"], unit: "bowl", kcal: 200, p: 22, c: 5, f: 10, fb: 1 },
  { id: 27, name: "Palak Paneer",          aliases: ["palak paneer","spinach paneer","saag paneer"], unit: "bowl", kcal: 250, p: 14, c: 12, f: 17, fb: 4 },
  { id: 28, name: "Aloo Sabzi",            aliases: ["aloo sabzi","potato curry","aloo ki sabzi","batata bhaji"], unit: "bowl", kcal: 180, p: 4, c: 28, f: 6, fb: 3 },
  { id: 29, name: "Mixed Veg Sabzi",       aliases: ["veg sabzi","mixed sabzi","sabzi","sabji","subzi","sabjee","mixed vegetables","mix veg"], unit: "bowl", kcal: 120, p: 4, c: 16, f: 5, fb: 4 },
  { id: 30, name: "Pav Bhaji",             aliases: ["pav bhaji","pavbhaji","pao bhaji"], unit: "serving", kcal: 420, p: 10, c: 60, f: 16, fb: 6 },
  { id: 31, name: "Chai (with milk)",      aliases: ["chai","tea","masala chai","adrak chai","cutting chai","ginger tea","milk tea"], unit: "cup", kcal: 60, p: 2, c: 8, f: 2, fb: 0 },
  { id: 32, name: "Lassi (Sweet)",         aliases: ["lassi","sweet lassi","mango lassi","dahi lassi"], unit: "glass", kcal: 180, p: 6, c: 30, f: 4, fb: 0.2 },
  { id: 33, name: "Buttermilk",            aliases: ["chaas","buttermilk","masala chaas","mattha"], unit: "glass", kcal: 40, p: 3, c: 5, f: 0.5, fb: 0 },
  { id: 34, name: "Milk (Full Fat)",       aliases: ["milk","doodh","full fat milk","full cream milk","whole milk"], unit: "cup", kcal: 150, p: 8, c: 12, f: 8, fb: 0 },
  { id: 35, name: "Curd / Dahi",           aliases: ["dahi","curd","yoghurt","yogurt","plain dahi"], unit: "katori", kcal: 60, p: 3.5, c: 4.5, f: 3, fb: 0 },
  { id: 36, name: "Raita",                 aliases: ["raita","boondi raita","cucumber raita","dahi raita"], unit: "katori", kcal: 65, p: 3, c: 8, f: 2, fb: 0.5 },
  { id: 37, name: "Samosa",                aliases: ["samosa","samosa chaat","aloo samosa"], unit: "piece", kcal: 130, p: 2.5, c: 16, f: 6.5, fb: 2 },
  { id: 38, name: "Vada Pav",              aliases: ["vada pav","vada pao","batata vada pav"], unit: "piece", kcal: 290, p: 6, c: 42, f: 11, fb: 3 },
  { id: 39, name: "Dhokla",                aliases: ["dhokla","khaman dhokla","besan dhokla"], unit: "piece", kcal: 80, p: 4, c: 12, f: 1.5, fb: 1.5 },
  { id: 40, name: "Jalebi",                aliases: ["jalebi","jalebi fafda"], unit: "piece", kcal: 75, p: 0.8, c: 17, f: 1.5, fb: 0 },
  { id: 41, name: "Gulab Jamun",           aliases: ["gulab jamun","gulab jamun mithai"], unit: "piece", kcal: 150, p: 2, c: 27, f: 5, fb: 0 },
  { id: 42, name: "Halwa",                 aliases: ["halwa","sooji halwa","atta halwa","moong dal halwa"], unit: "katori", kcal: 250, p: 4, c: 36, f: 10, fb: 1 },
  { id: 43, name: "Egg (Boiled)",          aliases: ["boiled egg","boiled eggs","anda","ande","anday","egg","eggs","hard boiled egg","soft boiled egg"], unit: "piece", kcal: 70, p: 6, c: 0.5, f: 5, fb: 0 },
  { id: 44, name: "Omelette",              aliases: ["omelette","egg omelette","masala omelette","anda omelette","omlette","omelet"], unit: "egg", kcal: 90, p: 6.5, c: 0.5, f: 7, fb: 0, g: 55 },
  { id: 45, name: "Khichdi",               aliases: ["khichdi","dal khichdi","masala khichdi","moong khichdi"], unit: "bowl", kcal: 200, p: 8, c: 34, f: 4, fb: 4 },
  { id: 46, name: "Pongal",                aliases: ["pongal","ven pongal","khara pongal","rice pongal"], unit: "bowl", kcal: 220, p: 6, c: 38, f: 5, fb: 2 },
  { id: 47, name: "Curd Rice",             aliases: ["curd rice","dahi chawal","thayir sadam","mosaranna"], unit: "bowl", kcal: 180, p: 6, c: 30, f: 4, fb: 1 },
  { id: 48, name: "Ghee",                  aliases: ["ghee","desi ghee"], unit: "tsp", kcal: 45, p: 0, c: 0, f: 5, fb: 0, modifier: true },
  { id: 49, name: "Butter",                aliases: ["butter","amul butter","white butter","makhan","salted butter"], unit: "tsp", kcal: 36, p: 0, c: 0, f: 4, fb: 0, modifier: true },
  { id: 50, name: "Oil",                   aliases: ["oil","cooking oil","refined oil","sarson ka tel","mustard oil"], unit: "tsp", kcal: 45, p: 0, c: 0, f: 5, fb: 0, modifier: true },
  { id: 51, name: "Banana",                aliases: ["banana","kela","plantain"], unit: "medium", kcal: 105, p: 1.3, c: 27, f: 0.3, fb: 3 },
  { id: 52, name: "Apple",                 aliases: ["apple","seb"], unit: "medium", kcal: 78, p: 0.4, c: 21, f: 0.2, fb: 3.5 },
  { id: 53, name: "Orange",                aliases: ["orange","santra","mosambi","sweet lime"], unit: "medium", kcal: 62, p: 1.2, c: 15, f: 0.2, fb: 3 },
  { id: 54, name: "Mixed Fruit",           aliases: ["fruit salad","mixed fruit","fruits"], unit: "bowl", kcal: 80, p: 1, c: 19, f: 0.3, fb: 3 },
  { id: 55, name: "Sprouts",               aliases: ["sprouts","moong sprouts","mixed sprouts","germinated moong"], unit: "bowl", kcal: 85, p: 7, c: 14, f: 0.5, fb: 5 },
  { id: 58, name: "Protein Shake",         aliases: ["protein shake","whey shake","protein smoothie","gym shake","whey","whey protein","whey scoop"], unit: "scoop", kcal: 120, p: 24, c: 3, f: 2, fb: 1 },
  { id: 59, name: "Bhel Puri",             aliases: ["bhel","bhelpuri","bhel puri","churmuri"], unit: "plate", kcal: 290, p: 6, c: 48, f: 8, fb: 4 },
  { id: 60, name: "Pani Puri",             aliases: ["pani puri","panipuri","golgappa","gol gappa","puchka","gupchup"], unit: "plate", kcal: 180, p: 3, c: 32, f: 5, fb: 2 },
  { id: 61, name: "Sev Puri",              aliases: ["sev puri","sevpuri","sev puri chaat"], unit: "plate", kcal: 320, p: 5, c: 42, f: 14, fb: 3 },
  { id: 62, name: "Dahi Puri",             aliases: ["dahi puri","dahipuri","dahi puri chaat"], unit: "plate", kcal: 280, p: 6, c: 38, f: 11, fb: 3 },
  { id: 64, name: "Biscuit",               aliases: ["biscuit","biscuits","marie biscuit","parle g","glucose biscuit","cookies"], unit: "piece", kcal: 40, p: 0.7, c: 6, f: 1.5, fb: 0.3 },
  { id: 65, name: "Rasam",                 aliases: ["rasam","charu","saaru","tomato rasam","pepper rasam"], unit: "bowl", kcal: 100, p: 3, c: 18, f: 2, fb: 1 },
  { id: 66, name: "Kadhi",                 aliases: ["kadhi","besan kadhi","kadhi pakoda","punjabi kadhi","gujarati kadhi"], unit: "bowl", kcal: 180, p: 6, c: 14, f: 11, fb: 1 },
  { id: 67, name: "Chole Bhature",         aliases: ["chole bhature","chole bhatura","chana bhatura","chole bhature plate"], unit: "plate", kcal: 650, p: 16, c: 80, f: 28, fb: 9 },
  { id: 68, name: "Chicken Breast",        aliases: ["chicken breast","grilled chicken","boiled chicken","tandoori chicken breast","skinless chicken","chicken breast piece"], unit: "100g", kcal: 165, p: 31, c: 0, f: 3.6, fb: 0, rawFactor: 0.73 },
  { id: 69, name: "Paneer (Raw/Grilled)",  aliases: ["paneer","raw paneer","grilled paneer","tandoori paneer","paneer cubes"], unit: "100g", kcal: 265, p: 18, c: 4, f: 20, fb: 0 },
  { id: 70, name: "Tofu",                  aliases: ["tofu","soya paneer","bean curd"], unit: "100g", kcal: 145, p: 15, c: 3, f: 8, fb: 1 },
  { id: 71, name: "Egg Whites",            aliases: ["egg white","egg whites","boiled egg whites","anda safedi"], unit: "white", kcal: 17, p: 3.6, c: 0.2, f: 0.1, fb: 0 },
  { id: 72, name: "Bread (slice)",         aliases: ["bread","bread slice","white bread","brown bread","toast","slice of bread","atta bread","wheat bread","whole wheat bread","multigrain bread"], unit: "slice", kcal: 75, p: 3, c: 14, f: 1, fb: 1 },
  { id: 73, name: "Honey",                 aliases: ["honey","shahad","madh"], unit: "tbsp", kcal: 64, p: 0, c: 17, f: 0, fb: 0 },
  { id: 74, name: "Jam",                   aliases: ["jam","mixed fruit jam","strawberry jam","marmalade"], unit: "tbsp", kcal: 56, p: 0, c: 14, f: 0, fb: 0.3 },
  { id: 75, name: "Sugar",                 aliases: ["sugar","cheeni","chini","white sugar"], unit: "tsp", kcal: 16, p: 0, c: 4, f: 0, fb: 0 },
  { id: 76, name: "Lemon Rice",            aliases: ["lemon rice","chitranna","nimmakaya annam"], unit: "bowl", kcal: 250, p: 4, c: 45, f: 7, fb: 2 },
  { id: 77, name: "Mango",                 aliases: ["mango","aam","mangoes","alphonso"], unit: "medium", kcal: 150, p: 1.4, c: 38, f: 0.6, fb: 2.6 },
  { id: 78, name: "Guava",                 aliases: ["guava","amrud","peru"], unit: "medium", kcal: 68, p: 2.6, c: 14, f: 1, fb: 5.4 },
  { id: 79, name: "Papaya",                aliases: ["papaya","papita"], unit: "bowl", kcal: 60, p: 0.7, c: 15, f: 0.2, fb: 2.5 },
  { id: 80, name: "Watermelon",            aliases: ["watermelon","tarbooz","tarbuj"], unit: "bowl", kcal: 46, p: 0.9, c: 11, f: 0.2, fb: 0.6 },
  { id: 81, name: "Grapes",                aliases: ["grapes","angoor","angur"], unit: "bowl", kcal: 70, p: 0.7, c: 18, f: 0.2, fb: 0.9 },
  { id: 82, name: "Pomegranate",           aliases: ["pomegranate","anaar","anar"], unit: "bowl", kcal: 100, p: 2, c: 22, f: 1, fb: 4 },
  { id: 83, name: "Chikoo",                aliases: ["chikoo","sapota","sapodilla","chiku"], unit: "medium", kcal: 83, p: 0.4, c: 20, f: 1, fb: 5.6 },
  { id: 84, name: "Pineapple",             aliases: ["pineapple","ananas"], unit: "bowl", kcal: 74, p: 0.8, c: 19, f: 0.2, fb: 2.3 },
  { id: 85, name: "Custard Apple",         aliases: ["custard apple","sitaphal","sharifa"], unit: "medium", kcal: 100, p: 2, c: 24, f: 0.3, fb: 4.4 },
  { id: 86, name: "Cucumber",              aliases: ["cucumber","kheera","kakdi","kakri"], unit: "bowl", kcal: 16, p: 0.7, c: 4, f: 0.1, fb: 0.5 },
  { id: 87, name: "Carrot",                aliases: ["carrot","gajar"], unit: "medium", kcal: 25, p: 0.6, c: 6, f: 0.1, fb: 1.7 },
  { id: 88, name: "Tomato",                aliases: ["tomato","tamatar"], unit: "medium", kcal: 22, p: 1, c: 5, f: 0.2, fb: 1.2 },
  { id: 89, name: "Green Salad",           aliases: ["green salad","salad","kachumber","veg salad"], unit: "plate", kcal: 40, p: 2, c: 8, f: 0.5, fb: 3 },
  { id: 90, name: "Chicken Tikka",         aliases: ["chicken tikka","tandoori chicken","chicken tikka dry","murgh tikka"], unit: "piece", kcal: 55, p: 9, c: 1, f: 2, fb: 0 },
  { id: 91, name: "Paneer Tikka (dry)",    aliases: ["paneer tikka","paneer tikka dry","grilled paneer tikka"], unit: "piece", kcal: 70, p: 4, c: 2, f: 5, fb: 0.3 },
  { id: 92, name: "Roasted Chana",         aliases: ["roasted chana","bhuna chana","roasted chickpeas","chana snack","phutana"], unit: "handful", kcal: 120, p: 7, c: 20, f: 2, fb: 5 },
  { id: 93, name: "Uttapam",               aliases: ["uttapam","uthappam","rava uttapam","onion uttapam"], unit: "piece", kcal: 175, p: 4, c: 25, f: 6, fb: 2 },
  { id: 94, name: "Maggi",                 aliases: ["maggi","maggie","masala noodles","instant noodles","2 minute noodles"], unit: "pack", kcal: 350, p: 8, c: 50, f: 13, fb: 2 },
  { id: 95, name: "Pizza (slice)",         aliases: ["pizza","pizza slice","cheese pizza","veg pizza","margherita"], unit: "slice", kcal: 285, p: 12, c: 36, f: 10, fb: 2 },
  { id: 96, name: "Ice Cream",             aliases: ["ice cream","icecream","vanilla ice cream","scoop of ice cream"], unit: "scoop", kcal: 140, p: 2.5, c: 16, f: 7, fb: 0.5 },
  { id: 97, name: "Matar Paneer",          aliases: ["matar paneer","mutter paneer","peas paneer","paneer matar"], unit: "bowl", kcal: 280, p: 14, c: 18, f: 16, fb: 4 },
  { id: 98, name: "Oats (Plain)",          aliases: ["oats","oatmeal","oats bowl","masala oats","overnight oats","quaker oats","quaker","rolled oats","plain oats"], unit: "bowl", kcal: 150, p: 5, c: 27, f: 3, fb: 4, g: 40 },
  { id: 99, name: "Peanut Butter",         aliases: ["peanut butter","pb","moongfali butter"], unit: "tbsp", kcal: 95, p: 4, c: 3, f: 8, fb: 1.5 },
  { id: 100, name: "Soya Chunks",          aliases: ["soya chunks","soya nuggets","nutrela","meal maker","soya","soyabean chunks"], unit: "bowl", kcal: 170, p: 26, c: 18, f: 1.5, fb: 6, g: 50 },
  { id: 101, name: "Sweet Potato",         aliases: ["sweet potato","shakarkandi","shakarkand"], unit: "medium", kcal: 115, p: 2, c: 27, f: 0.2, fb: 4 },
  { id: 102, name: "Brown Rice",           aliases: ["brown rice","brown chawal"], unit: "cup", kcal: 215, p: 5, c: 45, f: 1.8, fb: 3.5, rawFactor: 2.6 },
  { id: 103, name: "Greek Yogurt",         aliases: ["greek yogurt","hung curd","hung yogurt","chakka","greek yoghurt"], unit: "cup", kcal: 100, p: 10, c: 6, f: 0.5, fb: 0 },
  { id: 104, name: "Quinoa",               aliases: ["quinoa","quinoa bowl"], unit: "bowl", kcal: 220, p: 8, c: 39, f: 4, fb: 5 },
  { id: 105, name: "Protein Bar",          aliases: ["protein bar","energy bar","yogabar","protein cookie"], unit: "bar", kcal: 200, p: 20, c: 22, f: 7, fb: 3 },
  { id: 106, name: "Grilled Fish",         aliases: ["grilled fish","fish fillet","basa","tilapia","fish tikka","grilled fish fillet"], unit: "fillet", kcal: 180, p: 30, c: 1, f: 6, fb: 0 },
  { id: 107, name: "Low-Fat Paneer",       aliases: ["low fat paneer","low-fat paneer","diet paneer","toned paneer","skimmed paneer","low fat cottage cheese"], unit: "100g", kcal: 160, p: 20, c: 5, f: 7, fb: 0 },
  { id: 108, name: "Low-Fat Milk",         aliases: ["toned milk","skimmed milk","skim milk","double toned milk","low fat milk","low-fat milk"], unit: "cup", kcal: 100, p: 8, c: 12, f: 2.5, fb: 0 },
  { id: 109, name: "Low-Fat Curd",         aliases: ["low fat curd","low-fat curd","low fat dahi","low fat yogurt","greek yogurt low fat","skimmed curd"], unit: "katori", kcal: 45, p: 4, c: 5, f: 1, fb: 0 },
  { id: 110, name: "High-Protein Peanut Butter", aliases: ["high protein peanut butter","hp peanut butter","protein peanut butter","pintola high protein","myfitness peanut butter","muscleblaze peanut butter","mb peanut butter"], unit: "tbsp", kcal: 88, p: 5, c: 3, f: 6, fb: 1 },
  { id: 111, name: "High-Protein Roti",    aliases: ["high protein roti","protein roti","high protein atta roti","multigrain protein roti"], unit: "piece", kcal: 100, p: 5, c: 15, f: 2, fb: 3 },
  { id: 112, name: "High-Protein Bread",   aliases: ["high protein bread","protein bread"], unit: "slice", kcal: 80, p: 6, c: 12, f: 1.5, fb: 2 },
  { id: 113, name: "Protein Chips",        aliases: ["protein chips","protein puffs","roasted protein chips","open secret"], unit: "pack", kcal: 120, p: 10, c: 12, f: 4, fb: 2 },
  { id: 114, name: "Protein Muesli",       aliases: ["protein muesli","high protein muesli","protein granola"], unit: "bowl", kcal: 200, p: 14, c: 28, f: 5, fb: 5 },
  { id: 115, name: "Creatine",             aliases: ["creatine","creatine monohydrate","creatine scoop"], unit: "scoop", kcal: 0, p: 0, c: 0, f: 0, fb: 0 },
  { id: 116, name: "BCAA / EAA",           aliases: ["bcaa","eaa","amino acids","intra workout drink"], unit: "scoop", kcal: 10, p: 0, c: 2, f: 0, fb: 0 },
  { id: 117, name: "Black Coffee",         aliases: ["black coffee","americano","espresso","kali coffee","black coffee without sugar"], unit: "cup", kcal: 5, p: 0.3, c: 0, f: 0, fb: 0 },
  { id: 118, name: "Green Tea",            aliases: ["green tea","green chai","matcha","lemon green tea"], unit: "cup", kcal: 2, p: 0, c: 0.5, f: 0, fb: 0 },
  { id: 119, name: "Chia Seeds",           aliases: ["chia seeds","chia","chiaseeds","chia seed"], unit: "tbsp", kcal: 58, p: 2, c: 5, f: 3.7, fb: 4, g: 12 },
  { id: 120, name: "Flax Seeds",           aliases: ["flax seeds","flaxseed","alsi","alsi seeds","linseed"], unit: "tbsp", kcal: 55, p: 1.9, c: 3, f: 4.3, fb: 2.8, g: 10 },
  { id: 121, name: "Pumpkin Seeds",        aliases: ["pumpkin seeds","pepitas","kaddu ke beej"], unit: "tbsp", kcal: 56, p: 3, c: 1, f: 4.9, fb: 0.6, g: 10 },
  { id: 122, name: "Dates",                aliases: ["dates","khajur","date","medjool dates","khajoor"], unit: "piece", kcal: 66, p: 0.4, c: 18, f: 0, fb: 1.6, g: 24 },
  { id: 123, name: "Bhakri (Jowar/Bajra)", aliases: ["bhakri","jowar bhakri","jawar bhakri","bajra bhakri","multigrain bhakri","bhakhri","jowar roti","bajra roti"], unit: "piece", kcal: 120, p: 3, c: 25, f: 1, fb: 3 },
  // Exception to the veg-default policy: bare "bhurji" stays on Egg Bhurji (150)
  // — common usage is overwhelmingly anda bhurji. Paneer needs the explicit word.
  { id: 124, name: "Paneer Bhurji",        aliases: ["paneer bhurji","paneer burji","scrambled paneer","paneer bhurjee","paneer ki bhurji","cottage cheese bhurji"], unit: "bowl", kcal: 300, p: 15, c: 8, f: 23, fb: 1.5 },
  { id: 125, name: "Sattu Drink",          aliases: ["sattu drink","sattu","sattu shake","sattu sharbat","sattu water"], unit: "glass", kcal: 110, p: 6.5, c: 16, f: 1.5, fb: 3 },
  { id: 126, name: "Mutton Biryani",       aliases: ["mutton biryani","mutton biriyani","gosht biryani","lamb biryani"], unit: "plate", kcal: 400, p: 16, c: 42, f: 17, fb: 2.5, g: 250 },
  { id: 127, name: "Broccoli",             aliases: ["broccoli","steamed broccoli","boiled broccoli"], unit: "cup", kcal: 31, p: 2.5, c: 6, f: 0.3, fb: 2.4, g: 90 },
  { id: 128, name: "Potato (Boiled)",      aliases: ["potato","boiled potato","aloo boiled","uble aloo","boiled aloo"], unit: "medium", kcal: 115, p: 2.5, c: 26, f: 0.1, fb: 2.4, g: 150 },
  { id: 129, name: "Muskmelon",            aliases: ["muskmelon","kharbuja","cantaloupe","melon"], unit: "cup", kcal: 53, p: 1.3, c: 13, f: 0.3, fb: 1.4, g: 150 },
  { id: 130, name: "Clear Whey",           aliases: ["clear whey","clear whey protein","clear protein","juicy whey"], unit: "scoop", kcal: 85, p: 20, c: 1, f: 0.2, fb: 0, g: 30 },
  { id: 131, name: "Honey Chilli Potato",  aliases: ["honey chilli potato","honey chili potato","chilli potato","honey potato","crispy honey potato"], unit: "plate", kcal: 350, p: 4, c: 45, f: 18, fb: 3 },
  { id: 132, name: "Coffee (with milk)",   aliases: ["coffee","milk coffee","filter coffee","instant coffee","nescafe","coffee with milk"], unit: "cup", kcal: 90, p: 2.5, c: 12, f: 3, fb: 0 },
  { id: 133, name: "Egg (Fried/Half Fry)", aliases: ["fried egg","half fry","egg half fry","half fried egg","anda fry","egg fry","sunny side up","bullseye egg"], unit: "piece", kcal: 90, p: 6.3, c: 0.4, f: 7, fb: 0 },
  { id: 134, name: "High-Protein Oats",    aliases: ["high protein oats","protein oats","yogabar oats","yoga bar oats","whey oats","protein oatmeal"], unit: "bowl", kcal: 145, p: 10.5, c: 22, f: 3.5, fb: 4, g: 40 },
  { id: 135, name: "Diet Cola",            aliases: ["diet coke","coke zero","diet pepsi","zero coke","diet cola","zero sugar cold drink"], unit: "can", kcal: 1, p: 0, c: 0, f: 0, fb: 0, g: 330 },
  { id: 136, name: "Cold Drink (Cola)",    aliases: ["coke","coca cola","thums up","pepsi","sprite","cold drink","soft drink","limca","fanta","mountain dew"], unit: "can", kcal: 140, p: 0, c: 35, f: 0, fb: 0, g: 330 },
  { id: 137, name: "Coconut Water",        aliases: ["coconut water","nariyal pani","daab water","tender coconut water"], unit: "glass", kcal: 40, p: 0.5, c: 9, f: 0, fb: 0, g: 200 },
  { id: 138, name: "Sauf / Jeera Water",   aliases: ["sauf water","saunf water","jeera water","fennel water","cumin water"], unit: "glass", kcal: 5, p: 0, c: 1, f: 0, fb: 0 },
  { id: 139, name: "Nimbu Pani (Sweet)",   aliases: ["nimbu pani","shikanji","lemon water with sugar","lemonade","sweet lime water"], unit: "glass", kcal: 60, p: 0, c: 15, f: 0, fb: 0 },
  { id: 140, name: "Bread Pakoda",         aliases: ["bread pakoda","bread pakora","stuffed bread pakora"], unit: "piece", kcal: 230, p: 6, c: 27, f: 11, fb: 2 },
  { id: 141, name: "Thalipeeth",           aliases: ["thalipeeth","bhajni thalipeeth","methi thalipeeth"], unit: "piece", kcal: 130, p: 4, c: 20, f: 4, fb: 3 },
  { id: 142, name: "Fafda",                aliases: ["fafda","fafda gathiya","phaphda"], unit: "piece", kcal: 45, p: 1, c: 5, f: 2.4, fb: 0.5 },
  { id: 143, name: "Gatte ki Sabzi",       aliases: ["gatte ki sabzi","gatta curry","gatte curry","besan gatta sabzi","gatte ki kadhi"], unit: "bowl", kcal: 250, p: 8, c: 25, f: 13, fb: 3 },
  { id: 144, name: "Dal Dhokli",           aliases: ["dal dhokli","daal dhokli","varan phal"], unit: "bowl", kcal: 300, p: 11, c: 45, f: 8, fb: 6 },
  { id: 145, name: "Aamras",               aliases: ["aamras","aam ras","mango pulp","amras"], unit: "katori", kcal: 150, p: 1, c: 35, f: 1, fb: 2, g: 150 },
  { id: 146, name: "Achar / Pickle",       aliases: ["achar","pickle","aam ka achar","mango pickle","lemon pickle","mixed pickle"], unit: "tbsp", kcal: 30, p: 0.3, c: 3, f: 2, fb: 0.5 },
  { id: 147, name: "Papad",                aliases: ["papad","papadum","appalam","fried papad","urad papad","roasted papad","urad dal papad","masala papad"], unit: "piece", kcal: 45, p: 2, c: 6, f: 1.5, fb: 0.5 },
  { id: 148, name: "Rasgulla",             aliases: ["rasgulla","rosogolla","rasgula","sponge rasgulla"], unit: "piece", kcal: 120, p: 2, c: 25, f: 1.5, fb: 0 },
  { id: 149, name: "Vada (Medu/Batata)",   aliases: ["vada","wada","medu vada","batata vada","aloo vada","urad vada"], unit: "piece", kcal: 140, p: 3, c: 15, f: 7, fb: 1.5 },
  { id: 150, name: "Egg Bhurji",           aliases: ["egg bhurji","anda bhurji","bhurji","egg bhurji pav","scrambled eggs","anda bhurji pav","egg burji"], unit: "egg", kcal: 100, p: 6.5, c: 2, f: 7.5, fb: 0.3 },
  { id: 151, name: "Almonds",              aliases: ["almond","almonds","badam","soaked almonds","roasted almonds","almond nuts"], unit: "piece", kcal: 7, p: 0.26, c: 0.24, f: 0.6, fb: 0.15, g: 1.2 },
  { id: 152, name: "Cashews",              aliases: ["cashew","cashews","kaju","roasted cashew","salted cashews","cashew nuts"], unit: "piece", kcal: 9, p: 0.3, c: 0.5, f: 0.7, fb: 0.05, g: 1.7 },
  { id: 153, name: "Walnut",               aliases: ["walnut","walnuts","akhrot","walnut half"], unit: "half", kcal: 13, p: 0.3, c: 0.3, f: 1.3, fb: 0.13, g: 2 },
  { id: 154, name: "Pistachios",           aliases: ["pistachio","pistachios","pista","salted pista"], unit: "piece", kcal: 4, p: 0.15, c: 0.2, f: 0.32, fb: 0.07, g: 0.7 },
  { id: 155, name: "Raisins",              aliases: ["raisins","kishmish","raisin","black raisins","munakka"], unit: "tbsp", kcal: 30, p: 0.3, c: 8, f: 0, fb: 0.4, g: 10 },
  { id: 156, name: "Anjeer (Dried Fig)",   aliases: ["anjeer","dried fig","dry fig","figs dried","dried anjeer"], unit: "piece", kcal: 20, p: 0.3, c: 5, f: 0.1, fb: 1, g: 8 },
  { id: 157, name: "Dried Apricot",        aliases: ["dried apricot","khubani","apricot dry","jardalu"], unit: "piece", kcal: 19, p: 0.3, c: 5, f: 0, fb: 0.6, g: 8 },
  { id: 158, name: "Makhana (Roasted)",    aliases: ["makhana","fox nuts","foxnuts","roasted makhana","phool makhana","lotus seeds"], unit: "bowl", kcal: 87, p: 2.4, c: 19, f: 0.3, fb: 3.5, g: 25 },
  { id: 159, name: "Peanuts (Roasted)",    aliases: ["peanuts","roasted peanuts","moongfali","groundnuts","salted peanuts","boiled peanuts"], unit: "handful", kcal: 170, p: 7.5, c: 5, f: 14.5, fb: 2.5, g: 30 },
  { id: 160, name: "Dry Coconut (Copra)",  aliases: ["dry coconut","copra","sukha nariyal","coconut slice dry","desiccated coconut"], unit: "piece", kcal: 99, p: 1, c: 3.7, f: 9.9, fb: 2.4, g: 15 },
  { id: 161, name: "Mixed Dry Fruits",     aliases: ["mixed dry fruits","dry fruits","mixed nuts","trail mix","dry fruit mix"], unit: "handful", kcal: 165, p: 4.5, c: 11, f: 12, fb: 2, g: 30 },
  { id: 162, name: "Prunes",               aliases: ["prunes","prune","dried plum","sukha aloo bukhara"], unit: "piece", kcal: 23, p: 0.2, c: 6, f: 0, fb: 0.7, g: 9.5 },
  { id: 163, name: "Sunflower Seeds",      aliases: ["sunflower seeds","surajmukhi seeds","sunflower seed"], unit: "tbsp", kcal: 58, p: 2.1, c: 2, f: 5.2, fb: 0.9, g: 10 },
  { id: 164, name: "Melon Seeds (Magaj)",  aliases: ["melon seeds","magaj","watermelon seeds","char magaj"], unit: "tbsp", kcal: 56, p: 2.8, c: 1, f: 4.7, fb: 0.5, g: 10 },
  { id: 165, name: "Dried Cranberries",    aliases: ["dried cranberries","cranberries","craisins"], unit: "tbsp", kcal: 32, p: 0.1, c: 8.2, f: 0.1, fb: 0.5, g: 10 },
  { id: 166, name: "Kaju Katli",           aliases: ["kaju katli","kaju barfi","cashew barfi","kaju katri"], unit: "piece", kcal: 60, p: 1, c: 7, f: 3.2, fb: 0.2, g: 15 },
  { id: 167, name: "Besan Ladoo",          aliases: ["besan ladoo","besan laddu","besan laddoo"], unit: "piece", kcal: 165, p: 3.5, c: 18, f: 9, fb: 1, g: 35 },
  { id: 168, name: "Motichoor Ladoo",      aliases: ["motichoor ladoo","boondi ladoo","motichur laddu","ladoo","laddu"], unit: "piece", kcal: 140, p: 2, c: 22, f: 5.5, fb: 0.5, g: 30 },
  { id: 169, name: "Rasmalai",             aliases: ["rasmalai","ras malai","rossomalai"], unit: "piece", kcal: 160, p: 5, c: 18, f: 7.5, fb: 0, g: 80 },
  { id: 170, name: "Milk Barfi",           aliases: ["barfi","burfi","milk barfi","khoya barfi","plain barfi","doodh barfi"], unit: "piece", kcal: 105, p: 2.5, c: 14, f: 4.5, fb: 0, g: 25 },
  { id: 171, name: "Peda",                 aliases: ["peda","pedha","milk peda","kesar peda","mathura peda"], unit: "piece", kcal: 110, p: 2.5, c: 15, f: 4.5, fb: 0, g: 25 },
  { id: 172, name: "Kheer",                aliases: ["kheer","rice kheer","payasam","payesh","seviyan kheer"], unit: "katori", kcal: 200, p: 5.5, c: 30, f: 7, fb: 0.3, g: 150 },
  { id: 173, name: "Gajar Halwa",          aliases: ["gajar halwa","gajar ka halwa","carrot halwa","gajrela"], unit: "katori", kcal: 250, p: 4, c: 30, f: 13, fb: 2.5, g: 120 },
  { id: 174, name: "Mysore Pak",           aliases: ["mysore pak","mysore pak sweet","mysurpa"], unit: "piece", kcal: 160, p: 1.5, c: 17, f: 10, fb: 0.3, g: 30 },
  { id: 175, name: "Soan Papdi",           aliases: ["soan papdi","son papdi","patisa","sohan papdi"], unit: "piece", kcal: 130, p: 1.5, c: 16, f: 7, fb: 0.3, g: 25 },
  { id: 176, name: "Sandesh",              aliases: ["sandesh","sondesh","bengali sandesh"], unit: "piece", kcal: 100, p: 3, c: 14, f: 3.5, fb: 0, g: 30 },
  { id: 177, name: "Chikki",               aliases: ["chikki","peanut chikki","til chikki","gud chikki","gajak"], unit: "piece", kcal: 100, p: 2, c: 13, f: 4.5, fb: 0.5, g: 20 },
  { id: 178, name: "Malpua",               aliases: ["malpua","malpuas","mal pua"], unit: "piece", kcal: 180, p: 2, c: 25, f: 8, fb: 0.3, g: 50 },
  { id: 179, name: "Modak (Steamed)",      aliases: ["modak","ukdiche modak","steamed modak","modak sweet"], unit: "piece", kcal: 110, p: 1.5, c: 18, f: 3.5, fb: 0.5, g: 40 },
  { id: 180, name: "Kulfi",                aliases: ["kulfi","malai kulfi","kesar kulfi","kulfi stick","matka kulfi"], unit: "stick", kcal: 150, p: 4, c: 17, f: 8, fb: 0, g: 70 },
  { id: 181, name: "Green Leafy Vegetables", aliases: ["green vegetable","green vegetables","green veg","hari sabzi","leafy vegetables","leafy greens","greens","palak","spinach","saag","methi leaves"], unit: "cup", kcal: 25, p: 3, c: 4, f: 0.3, fb: 2.5, g: 100 },
  { id: 182, name: "Palak Sabzi",            aliases: ["palak sabzi","palak sabji","palak ki sabzi","spinach sabzi","palak bhaji","saag sabzi","methi sabzi","methi bhaji"], unit: "bowl", kcal: 120, p: 4.5, c: 8, f: 8, fb: 4 },
  { id: 183, name: "Chicken Paratha",        aliases: ["chicken paratha","murgh paratha","non veg paratha","chicken stuffed paratha"], unit: "piece", kcal: 310, p: 15, c: 30, f: 14, fb: 2 },
  { id: 184, name: "Keema Paratha",          aliases: ["keema paratha","mutton paratha","mince paratha","qeema paratha"], unit: "piece", kcal: 330, p: 16, c: 30, f: 16, fb: 2 },
  { id: 185, name: "Egg Paratha",            aliases: ["egg paratha","anda paratha","egg stuffed paratha","anda wala paratha"], unit: "piece", kcal: 280, p: 12, c: 28, f: 13, fb: 2 },
  // --- INDB promotion batch (2026-07-20): values from the lab-analyzed
  // foods_reference table (rows passed the 4/4/9 macro-energy identity check).
  // Bare category words follow the veg-default policy: pulao, sandwich,
  // manchurian, noodles, pakora, kachori, frankie -> veg variant.
  { id: 187, name: "Methi Thepla",           aliases: ["methi thepla","thepla","theplas","gujarati thepla","dhebra"], unit: "piece", kcal: 126, p: 3.3, c: 15.1, f: 5.8, fb: 2.8 },
  { id: 188, name: "Besan Chilla",           aliases: ["besan chilla","besan cheela","chilla","cheela","besan ka chilla","moong dal chilla"], unit: "piece", kcal: 71, p: 4.1, c: 10.9, f: 1.5, fb: 2.2 },
  { id: 189, name: "Aloo Paratha",           aliases: ["aloo paratha","aloo ka paratha","alu paratha","potato paratha","aloo parantha"], unit: "piece", kcal: 191, p: 3.5, c: 22.3, f: 9.5, fb: 3.9 },
  { id: 190, name: "Paneer Paratha",         aliases: ["paneer paratha","paneer ka paratha","paneer parantha"], unit: "piece", kcal: 224, p: 6.8, c: 20.7, f: 12.4, fb: 3.4 },
  { id: 191, name: "Rava Dosa",              aliases: ["rava dosa","suji dosa","sooji dosa","semolina dosa"], unit: "piece", kcal: 167, p: 5.4, c: 24.1, f: 5.2, fb: 3 },
  { id: 192, name: "Chicken Korma",          aliases: ["chicken korma","murgh korma","chicken kurma"], unit: "bowl", kcal: 513, p: 34.1, c: 18.8, f: 33.6, fb: 6.3 },
  { id: 193, name: "Mutton Korma",           aliases: ["mutton korma","gosht korma","mutton kurma"], unit: "bowl", kcal: 424, p: 26, c: 9.3, f: 31.3, fb: 2.9 },
  { id: 195, name: "Keema Curry",            aliases: ["keema","keema curry","mutton keema","matar keema","keema matar","kheema"], unit: "bowl", kcal: 457, p: 29, c: 21.5, f: 28, fb: 10.2 },
  { id: 196, name: "Prawn Curry",            aliases: ["prawn curry","jhinga curry","prawns curry","shrimp curry","prawn masala"], unit: "bowl", kcal: 313, p: 24.4, c: 8.9, f: 19.8, fb: 4.5 },
  { id: 197, name: "Tandoori Fish",          aliases: ["tandoori fish","fish tandoori","tandoori pomfret"], unit: "piece", kcal: 224, p: 26.1, c: 5.5, f: 10.8, fb: 1.4 },
  { id: 198, name: "Seekh Kebab (Mutton)",   aliases: ["seekh kebab","seekh kabab","mutton seekh kebab","mutton seekh"], unit: "piece", kcal: 60, p: 5.1, c: 1.4, f: 3.8, fb: 0.8 },
  { id: 199, name: "Boti Kebab (Mutton)",    aliases: ["boti kebab","boti kabab","mutton boti"], unit: "piece", kcal: 73, p: 5, c: 1.7, f: 5.1, fb: 0.4 },
  { id: 200, name: "Jeera Pulao",            aliases: ["jeera pulao","jeera rice","zeera pulao","cumin rice"], unit: "plate", kcal: 366, p: 6.7, c: 63.9, f: 8.7, fb: 3.8 },
  { id: 201, name: "Veg Pulao",              aliases: ["veg pulao","pulao","pulav","vegetable pulao","mixed veg pulao","veg pulav"], unit: "plate", kcal: 496, p: 11.9, c: 76.7, f: 14.6, fb: 11.7 },
  { id: 202, name: "Matar Pulao",            aliases: ["matar pulao","peas pulao","mutter pulao","matar pulav"], unit: "plate", kcal: 514, p: 18.4, c: 86.9, f: 9, fb: 15.2 },
  { id: 203, name: "Makki ki Roti",          aliases: ["makki ki roti","makki roti","makke ki roti","corn roti"], unit: "piece", kcal: 224, p: 3, c: 20.6, f: 14.3, fb: 4.4 },
  { id: 204, name: "Sarson ka Saag",         aliases: ["sarson ka saag","sarson da saag","sarson saag","mustard greens"], unit: "bowl", kcal: 124, p: 4.3, c: 7.5, f: 8.3, fb: 5.2 },
  { id: 205, name: "Veg Sandwich (Grilled)", aliases: ["veg sandwich","sandwich","grilled sandwich","tomato sandwich","bombay sandwich","veg grilled sandwich"], unit: "sandwich", kcal: 146, p: 4.8, c: 16.3, f: 7.2, fb: 1.5 },
  { id: 206, name: "Banana Milkshake",       aliases: ["banana milkshake","banana shake","kela shake"], unit: "glass", kcal: 226, p: 6.4, c: 31.6, f: 8.2, fb: 0.9 },
  { id: 207, name: "Mango Milkshake",        aliases: ["mango milkshake","mango shake","aam shake","mango milk shake"], unit: "glass", kcal: 202, p: 6.1, c: 25.7, f: 8.3, fb: 0.9 },
  { id: 208, name: "Paneer Kathi Roll",      aliases: ["paneer kathi roll","paneer roll","kathi roll","kaathi roll","paneer frankie","frankie","veg roll","veg frankie"], unit: "piece", kcal: 424, p: 10.3, c: 29.8, f: 29, fb: 3.6 },

  // --- Restaurant Indian-Chinese + fried street snacks (2026-07-20): INDB rows
  // for these had whole-recipe oil yields (e.g. 718 kcal/72.8g fat per kachori),
  // so values below are curated from standard published averages instead.
  // Verify against INDB per-100g or labels before trusting for clinical use.
  { id: 194, name: "Veg Korma (Navratan)",   aliases: ["veg korma","korma","navratan korma","vegetable korma","veg kurma"], unit: "bowl", kcal: 320, p: 6, c: 22, f: 23, fb: 3 },
  { id: 209, name: "Chilli Chicken",         aliases: ["chilli chicken","chilly chicken","chili chicken","dry chilli chicken"], unit: "bowl", kcal: 330, p: 22, c: 15, f: 20, fb: 1 },
  { id: 210, name: "Chicken Manchurian",     aliases: ["chicken manchurian","manchurian chicken"], unit: "bowl", kcal: 300, p: 18, c: 16, f: 18, fb: 1 },
  { id: 211, name: "Veg Manchurian",         aliases: ["veg manchurian","manchurian","gobi manchurian","cabbage manchurian","veg manchurian gravy"], unit: "bowl", kcal: 250, p: 5, c: 28, f: 13, fb: 2 },
  { id: 212, name: "Hakka Noodles (Veg)",    aliases: ["hakka noodles","veg noodles","noodles","chowmein","chow mein","veg chowmein"], unit: "plate", kcal: 400, p: 9, c: 55, f: 15, fb: 3 },
  { id: 213, name: "Chicken Noodles",        aliases: ["chicken noodles","chicken hakka noodles","chicken chowmein"], unit: "plate", kcal: 460, p: 20, c: 55, f: 17, fb: 3 },
  { id: 214, name: "Onion Pakora",           aliases: ["onion pakora","pyaz pakora","pakora","pakoda","pakode","bhajiya","onion bhajji","kanda bhaji"], unit: "piece", kcal: 60, p: 1.5, c: 5, f: 3.8, fb: 0.7 },
  { id: 215, name: "Spring Roll (Veg)",      aliases: ["spring roll","veg spring roll","spring rolls"], unit: "piece", kcal: 120, p: 3, c: 15, f: 5.3, fb: 1 },
  { id: 216, name: "Khasta Kachori",         aliases: ["kachori","khasta kachori","kachauri","pyaz kachori"], unit: "piece", kcal: 210, p: 4, c: 23, f: 11, fb: 1.5 },
  { id: 217, name: "Hara Bhara Kebab",       aliases: ["hara bhara kebab","hara bhara kabab","veg kebab","hara kebab"], unit: "piece", kcal: 70, p: 2, c: 9, f: 2.9, fb: 1.5 },

  // --- Branded protein products (2026-07-20): values from manufacturer labels
  // (uncertain brands verified via published label data on 2026-07-20).
  // Generic fallbacks stay on: Protein Shake 58, Protein Bar 105, Creatine 115,
  // Clear Whey 130, Protein Muesli 114. Brand word required to land here.
  { id: 218, name: "ON Gold Standard Whey",     aliases: ["on whey","optimum nutrition whey","gold standard whey","gold standard","on gold standard"], unit: "scoop", kcal: 120, p: 24, c: 3, f: 1.5, fb: 0, g: 30 },
  { id: 219, name: "ON Gold Standard Isolate",  aliases: ["on isolate","optimum nutrition isolate","gold standard isolate"], unit: "scoop", kcal: 110, p: 25, c: 2, f: 0.5, fb: 0, g: 31 },
  { id: 220, name: "ON Serious Mass",           aliases: ["serious mass","on serious mass","on mass gainer"], unit: "scoop", kcal: 625, p: 25, c: 126, f: 2.2, fb: 2, g: 167 },
  { id: 221, name: "MuscleBlaze Biozyme Whey",  aliases: ["mb whey","muscleblaze whey","biozyme","biozyme whey","biozyme performance whey"], unit: "scoop", kcal: 136, p: 25, c: 4.4, f: 2.2, fb: 0, g: 36 },
  { id: 222, name: "MuscleBlaze Whey Isolate",  aliases: ["mb isolate","muscleblaze isolate","biozyme isolate"], unit: "scoop", kcal: 120, p: 27, c: 1.5, f: 1, fb: 0, g: 33 },
  { id: 223, name: "MuscleBlaze Raw Whey",      aliases: ["mb raw whey","muscleblaze raw whey","raw whey concentrate"], unit: "scoop", kcal: 120, p: 24, c: 2.4, f: 1.8, fb: 0, g: 30 },
  { id: 224, name: "MuscleBlaze Mass Gainer XXL", aliases: ["mb gainer","muscleblaze gainer","mass gainer xxl","mb mass gainer"], unit: "scoop", kcal: 280, p: 11, c: 52, f: 3, fb: 1, g: 75 },
  { id: 225, name: "MuscleBlaze Protein Bar",   aliases: ["mb protein bar","muscleblaze bar","muscleblaze protein bar"], unit: "bar", kcal: 230, p: 20, c: 22, f: 7, fb: 2, g: 60 },
  { id: 226, name: "SuperYou Protein Wafer",    aliases: ["superyou wafer","superyou protein wafer","super you wafer","superyou bar","protein wafer"], unit: "bar", kcal: 190, p: 10, c: 16, f: 10, fb: 3, g: 40 },
  { id: 227, name: "SuperYou Mega Wafer",       aliases: ["superyou mega wafer","superyou mega protein wafer","mega protein wafer","superyou 20g"], unit: "bar", kcal: 285, p: 20, c: 20, f: 14, fb: 4.8, g: 60 },
  { id: 228, name: "Avvatar Whey",              aliases: ["avvatar whey","avvatar protein","avvatar absolute whey","avvatar"], unit: "scoop", kcal: 130, p: 25, c: 4, f: 2, fb: 0, g: 30 },
  { id: 229, name: "MyProtein Impact Whey",     aliases: ["myprotein whey","impact whey","my protein whey","myprotein"], unit: "scoop", kcal: 103, p: 21, c: 2, f: 1.9, fb: 0, g: 25 },
  { id: 230, name: "MyProtein Impact Isolate",  aliases: ["myprotein isolate","impact isolate","impact whey isolate"], unit: "scoop", kcal: 93, p: 23, c: 0.6, f: 0.3, fb: 0, g: 25 },
  { id: 231, name: "GNC Pro Performance Whey",  aliases: ["gnc whey","gnc pro performance","gnc protein"], unit: "scoop", kcal: 130, p: 24, c: 5.5, f: 1.5, fb: 0, g: 33 },
  { id: 232, name: "GNC AMP Gold Isolate",      aliases: ["gnc isolate","amp gold","gnc amp gold"], unit: "scoop", kcal: 110, p: 24, c: 3, f: 0.5, fb: 0, g: 30 },
  { id: 233, name: "Nakpro Gold Whey",          aliases: ["nakpro","nakpro whey","nakpro gold"], unit: "scoop", kcal: 137, p: 25.5, c: 4.5, f: 2, fb: 0, g: 35 },
  { id: 234, name: "Yoga Bar 20g Protein Bar",  aliases: ["yoga bar 20g","yogabar 20g","yogabar 20g protein bar","yoga bar protein bar"], unit: "bar", kcal: 230, p: 20, c: 23, f: 6.6, fb: 2, g: 60 },
  { id: 235, name: "Yoga Bar 10g Protein Bar",  aliases: ["yoga bar 10g","yogabar 10g","yogabar 10g protein bar"], unit: "bar", kcal: 150, p: 10, c: 18, f: 4.4, fb: 1.5, g: 38 },
  { id: 236, name: "Yoga Bar Protein Muesli",   aliases: ["yogabar muesli","yoga bar muesli","yogabar protein muesli"], unit: "serving", kcal: 190, p: 10.5, c: 26, f: 4.4, fb: 3, g: 50 },
  { id: 237, name: "RiteBite Max Protein Ultimate", aliases: ["ritebite ultimate","max protein ultimate","ritebite 30g bar","max protein 30g bar"], unit: "bar", kcal: 361, p: 30, c: 45, f: 14.7, fb: 5, g: 100 },
  { id: 238, name: "RiteBite Max Protein Daily", aliases: ["ritebite daily","max protein daily","ritebite 10g bar","ritebite bar"], unit: "bar", kcal: 173, p: 10, c: 22, f: 5.4, fb: 2.5, g: 50 },
  { id: 239, name: "RiteBite Max Protein Active", aliases: ["ritebite active","max protein active","max protein bar"], unit: "bar", kcal: 250, p: 20, c: 28, f: 7, fb: 3, g: 70 },
  { id: 240, name: "The Whole Truth 20g Bar",   aliases: ["whole truth 20g","twt 20g bar","whole truth protein bar","the whole truth bar","twt bar"], unit: "bar", kcal: 340, p: 20, c: 21, f: 19, fb: 5.8, g: 67 },
  { id: 241, name: "The Whole Truth 12g Bar",   aliases: ["whole truth 12g","twt 12g bar","whole truth mini bar"], unit: "bar", kcal: 240, p: 12, c: 18, f: 13.5, fb: 4, g: 52 },
  { id: 242, name: "Protinex",                  aliases: ["protinex","protinex powder","protinex doodh","protinex milk"], unit: "serving", kcal: 125, p: 11, c: 17, f: 1.4, fb: 0, g: 34 },

  // --- Gap-trail promotions (2026-07-20): both surfaced by real users within
  // hours of the gap logger going live. Not in INDB — curated from standard
  // published values. "Dal baati" should parse as TWO items (Dal 17 + Baati).
  { id: 243, name: "Baati (ghee-dipped)",       aliases: ["baati","bati","rajasthani baati","churma baati"], unit: "piece", kcal: 200, p: 4, c: 26, f: 8.5, fb: 2.5, g: 45 },
  { id: 244, name: "Ladi Pav (Bun)",            aliases: ["pav","ladi pav","bun","bread bun","maska bun","pao"], unit: "piece", kcal: 120, p: 4, c: 22, f: 1.6, fb: 1, g: 40 },
  { id: 245, name: "Cheese (Processed)",        aliases: ["cheese","cheese slice","amul cheese","processed cheese","cheese cube","cheez"], unit: "slice", kcal: 62, p: 3.7, c: 0.8, f: 5, fb: 0, g: 20 },
  { id: 246, name: "Schezwan Dosa",             aliases: ["schezwan dosa","schezwan sada dosa","szechuan dosa","chinese dosa","schezvan dosa"], unit: "piece", kcal: 280, p: 5, c: 40, f: 11, fb: 2 },
  { id: 247, name: "Cheese Dosa",               aliases: ["cheese dosa","cheese sada dosa"], unit: "piece", kcal: 250, p: 7, c: 30, f: 11, fb: 1.5 },

  // --- Gap-trail promotions, label-verified 2026-07-20 ---
  // Chocos 373 kcal/100g; a 30g bowl is the common serving.
  { id: 248, name: "Chocos (Kellogg's)",        aliases: ["chocos","choco flakes","chocos cereal","kelloggs chocos"], unit: "bowl", kcal: 112, p: 2.7, c: 25.1, f: 0.9, fb: 1.5, g: 30 },
  // Munch 435 kcal/100g; the common ₹10 bar is ~20g. Munch Max is roughly double.
  { id: 249, name: "Munch (Nestlé)",            aliases: ["munch","munch chocolate","nestle munch","munch bar"], unit: "piece", kcal: 87, p: 1.2, c: 12, f: 4.2, fb: 0.3, g: 20 },
  { id: 250, name: "Mutton Curry",              aliases: ["mutton curry","gosht curry","mutton masala","mutton gravy","lamb curry","mutton rogan josh","rogan josh"], unit: "bowl", kcal: 350, p: 24, c: 8, f: 25, fb: 1.5 },

  // --- Momos (2026-07-20): bare "momo/momos" defaults to steamed veg per
  // veg-default policy. Chicken needs the explicit protein word.
  { id: 251, name: "Momos (Steamed Veg)",       aliases: ["momo","momos","steam momo","steamed momos","steamed momo","veg momos","veg momo","dim sum","veg steamed momos"], unit: "piece", kcal: 35, p: 1.2, c: 5, f: 1, fb: 0.5 },
  { id: 252, name: "Momos (Chicken)",            aliases: ["chicken momo","chicken momos","non veg momo","non veg momos","steamed chicken momos","chicken steam momo"], unit: "piece", kcal: 45, p: 3, c: 4, f: 1.5, fb: 0.3 },
  { id: 253, name: "Momos (Fried)",              aliases: ["fried momo","fried momos","tawa momo","tawa momos","kurkure momos","crispy momo","crispy momos","deep fried momos"], unit: "piece", kcal: 65, p: 1.5, c: 6, f: 3.5, fb: 0.5 },
  { id: 254, name: "Momos (Tandoori)",           aliases: ["tandoori momo","tandoori momos","afghani momo","afghani momos","malai momos","peri peri momos"], unit: "piece", kcal: 55, p: 2, c: 5, f: 2.8, fb: 0.4 },
  { id: 255, name: "Momos (Chilli/Gravy)",       aliases: ["chilli momo","chilli momos","gravy momo","gravy momos","schezwan momos","szechuan momos","saucy momos"], unit: "piece", kcal: 60, p: 1.8, c: 7, f: 2.8, fb: 0.6 },

  // --- Street chaat (2026-07-20). Chaat plates are assembled, not single-
  // ingredient: values are the standard vendor plate, not per-component.
  { id: 256, name: "Aloo Tikki",                 aliases: ["aloo tikki","alu tikki","tikki","potato tikki","aloo patty"], unit: "piece", kcal: 150, p: 3, c: 22, f: 5.5, fb: 2.5, g: 70 },
  { id: 257, name: "Aloo Tikki Chaat",           aliases: ["aloo tikki chaat","tikki chaat","aloo tikki plate"], unit: "plate", kcal: 320, p: 7, c: 45, f: 12, fb: 5 },
  { id: 258, name: "Papdi Chaat",                aliases: ["papdi chaat","papri chaat","papdi","papadi chaat"], unit: "plate", kcal: 330, p: 7, c: 42, f: 15, fb: 4 },
  { id: 259, name: "Dahi Vada",                  aliases: ["dahi vada","dahi bhalla","dahi bada","dahi wada","thayir vadai"], unit: "piece", kcal: 120, p: 4, c: 14, f: 5, fb: 1.5 },
  { id: 260, name: "Raj Kachori",                aliases: ["raj kachori","raj kachauri","raj kachodi"], unit: "piece", kcal: 380, p: 8, c: 45, f: 18, fb: 4 },
  { id: 261, name: "Ragda Pattice",              aliases: ["ragda pattice","ragda patties","ragda","ragda chaat"], unit: "plate", kcal: 400, p: 12, c: 58, f: 13, fb: 8 },
  { id: 262, name: "Chinese Bhel",               aliases: ["chinese bhel","chinese bhel puri","crispy chinese bhel"], unit: "plate", kcal: 300, p: 6, c: 40, f: 13, fb: 3 },

  // --- Mumbai / Maharashtra / Gujarat street ---
  { id: 263, name: "Misal Pav",                  aliases: ["misal pav","misal","missal pav","usal pav","sev usal"], unit: "plate", kcal: 450, p: 16, c: 58, f: 17, fb: 11 },
  { id: 264, name: "Dabeli",                     aliases: ["dabeli","kutchi dabeli","kacchi dabeli"], unit: "piece", kcal: 250, p: 5, c: 36, f: 9.5, fb: 3 },
  { id: 265, name: "Sabudana Khichdi",           aliases: ["sabudana khichdi","sabudana","sago khichdi","sabudana kichdi","javvarisi"], unit: "bowl", kcal: 300, p: 4, c: 48, f: 11, fb: 2 },
  { id: 266, name: "Sabudana Vada",              aliases: ["sabudana vada","sago vada","sabudana wada"], unit: "piece", kcal: 120, p: 2, c: 16, f: 5.5, fb: 1 },
  { id: 267, name: "Khandvi",                    aliases: ["khandvi","khandavi","surali vadi"], unit: "piece", kcal: 35, p: 1.5, c: 4, f: 1.5, fb: 0.5 },
  { id: 268, name: "Khakhra",                    aliases: ["khakhra","khakra","methi khakhra","masala khakhra"], unit: "piece", kcal: 40, p: 1.3, c: 6, f: 1.2, fb: 1, g: 10 },
  { id: 269, name: "Litti Chokha",               aliases: ["litti chokha","litti","bihari litti","litti with chokha"], unit: "piece", kcal: 180, p: 5, c: 26, f: 6.5, fb: 3 },

  // --- Rolls, breads, fast food ---
  { id: 270, name: "Egg Roll",                   aliases: ["egg roll","anda roll","egg kathi roll","egg frankie"], unit: "piece", kcal: 350, p: 13, c: 34, f: 18, fb: 2 },
  { id: 271, name: "Chicken Shawarma",           aliases: ["shawarma","chicken shawarma","shawarma roll","shwarma"], unit: "piece", kcal: 450, p: 26, c: 40, f: 21, fb: 3 },
  { id: 272, name: "Amritsari Kulcha",           aliases: ["kulcha","amritsari kulcha","aloo kulcha","paneer kulcha"], unit: "piece", kcal: 330, p: 7, c: 45, f: 13, fb: 3 },
  { id: 273, name: "Chole Kulche",               aliases: ["chole kulche","chana kulcha","kulche chole","chole kulcha"], unit: "plate", kcal: 500, p: 15, c: 70, f: 18, fb: 10 },
  { id: 275, name: "Veg Burger",                 aliases: ["burger","veg burger","aloo tikki burger","veggie burger"], unit: "piece", kcal: 350, p: 9, c: 48, f: 13, fb: 3 },
  { id: 276, name: "Chicken Burger",             aliases: ["chicken burger","chicken patty burger","zinger burger"], unit: "piece", kcal: 450, p: 22, c: 44, f: 21, fb: 2.5 },
  { id: 277, name: "French Fries",               aliases: ["french fries","fries","finger chips","peri peri fries","salted fries"], unit: "serving", kcal: 320, p: 4, c: 42, f: 15, fb: 4, g: 100 },
  { id: 278, name: "Pasta (Red Sauce)",          aliases: ["pasta","red sauce pasta","arrabbiata pasta","tomato pasta","penne pasta"], unit: "bowl", kcal: 350, p: 11, c: 55, f: 9, fb: 4 },
  { id: 279, name: "Pasta (White Sauce)",        aliases: ["white sauce pasta","alfredo pasta","creamy pasta","cheesy pasta"], unit: "bowl", kcal: 430, p: 13, c: 50, f: 20, fb: 3 },

  // --- Indo-Chinese starters ---
  { id: 280, name: "Chilli Paneer",              aliases: ["chilli paneer","chili paneer","chilly paneer","paneer chilli dry"], unit: "bowl", kcal: 320, p: 16, c: 18, f: 21, fb: 2 },
  { id: 281, name: "Chicken Lollipop",           aliases: ["chicken lollipop","lollipop","chicken lolipop","drums of heaven"], unit: "piece", kcal: 90, p: 7, c: 3, f: 6, fb: 0.2 },

  // --- Mithai & desserts ---
  { id: 283, name: "Puran Poli",                 aliases: ["puran poli","puranpoli","holige","obbattu"], unit: "piece", kcal: 250, p: 6, c: 42, f: 7, fb: 3 },
  { id: 284, name: "Shrikhand",                  aliases: ["shrikhand","srikhand","kesar shrikhand","amrakhand"], unit: "bowl", kcal: 250, p: 7, c: 35, f: 9, fb: 0.3, g: 100 },
  { id: 285, name: "Rabri",                      aliases: ["rabri","rabdi","basundi","malai rabri"], unit: "bowl", kcal: 230, p: 7, c: 26, f: 11, fb: 0, g: 100 },
  { id: 286, name: "Imarti",                     aliases: ["imarti","jangiri","amriti"], unit: "piece", kcal: 110, p: 1.2, c: 24, f: 2.5, fb: 0.2 },
  { id: 287, name: "Ghevar",                     aliases: ["ghevar","gheavar","malai ghevar","rajasthani ghevar"], unit: "piece", kcal: 300, p: 4, c: 40, f: 14, fb: 0.5 },
  { id: 288, name: "Falooda",                    aliases: ["falooda","faluda","kulfi falooda","rose falooda"], unit: "glass", kcal: 350, p: 8, c: 55, f: 11, fb: 1 },

  // --- Street drinks ---
  { id: 289, name: "Cold Coffee",                aliases: ["cold coffee","iced coffee","cold coffee with ice cream","frappe"], unit: "glass", kcal: 250, p: 7, c: 35, f: 9, fb: 0 },
  { id: 290, name: "Sugarcane Juice",            aliases: ["sugarcane juice","ganne ka ras","ganna juice","sugar cane juice"], unit: "glass", kcal: 180, p: 0.5, c: 45, f: 0.2, fb: 0.5, g: 250 },
  { id: 291, name: "Aam Panna",                  aliases: ["aam panna","aam pana","raw mango drink","panna"], unit: "glass", kcal: 120, p: 0.5, c: 30, f: 0.2, fb: 0.8 },
  { id: 292, name: "Bhutta (Roasted Corn)",      aliases: ["bhutta","roasted corn","bhutta corn","corn on the cob","challi"], unit: "piece", kcal: 110, p: 4, c: 24, f: 1.3, fb: 3 },
  { id: 293, name: "Masala Corn (Cup)",          aliases: ["masala corn","sweet corn cup","corn cup","buttered corn","corn chaat"], unit: "cup", kcal: 180, p: 5, c: 30, f: 5.5, fb: 4 },

  // --- Brand range expansion, label-verified 2026-07-20 ---
  // SuperYou PRO is FERMENTED YEAST protein, not whey — but users call every
  // powder "whey", and without that alias "superyou whey protein" fell through
  // to the wafer bar (10g protein) and under-counted by more than half.
  // Label: 36g scoop, 124 kcal, 24g protein, 4g carb, 1.2g fat, 3g fibre.
  { id: 294, name: "SuperYou PRO (Yeast Protein)", aliases: ["superyou","super you","superyou pro","superyou protein","superyou whey","superyou whey protein","superyou protein powder","superyou powder","fermented yeast protein","superyou chocolate protein","superyou cold coffee protein","superyou kesar badam","superyou strawberry protein","superyou vanilla protein"], unit: "scoop", kcal: 124, p: 24, c: 4, f: 1.2, fb: 3, g: 36 },
  { id: 295, name: "SuperYou PRO Unflavoured",   aliases: ["superyou unflavoured","superyou unflavored","superyou plain","superyou pro unflavoured"], unit: "scoop", kcal: 130, p: 27, c: 3, f: 1.2, fb: 3, g: 36 },
  { id: 296, name: "SuperYou Mini Protein Wafer", aliases: ["superyou mini wafer","superyou mini","mini protein wafer","superyou 5g wafer"], unit: "bar", kcal: 95, p: 5, c: 11, f: 4.5, fb: 1.5, g: 20 },
  { id: 297, name: "SuperYou Protein Chips",     aliases: ["superyou chips","superyou protein chips","superyou multigrain chips","superyou baked chips"], unit: "pack", kcal: 165, p: 10, c: 19, f: 5, fb: 3, g: 40 },

  // MuscleBlaze range beyond Biozyme/Raw/Gainer already at 221-225.
  { id: 298, name: "MuscleBlaze Whey Gold",      aliases: ["mb whey gold","muscleblaze whey gold","whey gold","mb gold"], unit: "scoop", kcal: 110, p: 25, c: 1.8, f: 0.5, fb: 0, g: 30 },
  { id: 299, name: "MuscleBlaze Fuel One Whey",  aliases: ["fuel one","fuel one whey","mb fuel one","muscleblaze fuel one","fuel one protein"], unit: "scoop", kcal: 133, p: 24, c: 5, f: 2.2, fb: 0, g: 33 },
  { id: 300, name: "MuscleBlaze Biozyme Iso-Zero", aliases: ["iso zero","iso-zero","biozyme iso zero","mb iso zero","muscleblaze iso zero"], unit: "scoop", kcal: 121, p: 27, c: 1.6, f: 0.5, fb: 0, g: 33 },
  // Biozyme Gold publishes 135.22 kcal / 26g protein but not carb+fat. The
  // 31 kcal not accounted for by protein is split at the ~3g carb / 2g fat
  // typical of the range; flagged here so a future label read can correct it.
  { id: 301, name: "MuscleBlaze Biozyme Gold",   aliases: ["biozyme gold","mb biozyme gold","muscleblaze biozyme gold","biozyme gold whey"], unit: "scoop", kcal: 135, p: 26, c: 3, f: 2, fb: 0, g: 35 },

  // The Whole Truth sells powders as well as the bars at 240/241. Without the
  // powder, "wholetruth cold coffee whey protein" collapsed onto the 20g BAR
  // (340 kcal, 20g protein) — same failure shape as SuperYou above: one brand,
  // several product forms, only one of them curated.
  // Label: 35g scoop, 134 kcal, 24.9g protein, 6.3g carb, 1.1g fat, 1.6g fibre.
  { id: 302, name: "The Whole Truth Whey (Flavoured)", aliases: ["wholetruth whey","whole truth whey","the whole truth whey","twt whey","wholetruth protein powder","whole truth protein powder","wholetruth cold coffee whey","whole truth cold coffee protein","twt protein powder"], unit: "scoop", kcal: 134, p: 24.9, c: 6.3, f: 1.1, fb: 1.6, g: 35 },
  { id: 303, name: "The Whole Truth Whey Concentrate (Unflavoured)", aliases: ["wholetruth unflavoured whey","whole truth whey concentrate","twt concentrate","wholetruth concentrate"], unit: "scoop", kcal: 125, p: 26, c: 2, f: 1.5, fb: 0, g: 32 },
  { id: 304, name: "The Whole Truth Whey Isolate",  aliases: ["wholetruth isolate","whole truth isolate","twt isolate","wholetruth whey isolate"], unit: "scoop", kcal: 130, p: 30, c: 1, f: 0.5, fb: 0, g: 34 },

  // "Chicken sandwich" was landing on Chicken Burger 276 — close, but a burger
  // is not a sandwich and the DB only had the veg one (205).
  { id: 305, name: "Chicken Sandwich",           aliases: ["chicken sandwich","grilled chicken sandwich","chicken mayo sandwich","chicken club sandwich"], unit: "sandwich", kcal: 320, p: 20, c: 30, f: 12, fb: 2 },
];

const FOOD_BY_ID = Object.fromEntries(FOODS.map(f => [f.id, f]));

module.exports = { FOODS, FOOD_BY_ID };
