// NutriDesi food database — 58 core Indian items with Hinglish aliases.
// Aliases are the single biggest lever on parse accuracy. Expand these over time.
// Fields: id, name, aliases[], unit, kcal, protein(p), carbs(c), fat(f), modifier?

const FOODS = [
  { id: 1,  name: "Roti / Chapati",       aliases: ["roti","chapati","phulka","chappati","fulka","chapatti","wheat roti"], unit: "piece", kcal: 89,  p: 2.6, c: 17, f: 1.1 },
  { id: 2,  name: "Paratha (Plain)",       aliases: ["paratha","plain paratha","tawa paratha","sada paratha"], unit: "piece", kcal: 155, p: 3.5, c: 26, f: 4.5 },
  { id: 3,  name: "Paratha (Stuffed)",     aliases: ["aloo paratha","gobi paratha","stuffed paratha","mixed paratha","paneer paratha"], unit: "piece", kcal: 260, p: 5.5, c: 38, f: 10 },
  { id: 4,  name: "Puri",                  aliases: ["puri","poori","puri bhaji"], unit: "piece", kcal: 110, p: 2, c: 13, f: 5.5 },
  { id: 5,  name: "Naan",                  aliases: ["naan","naan bread","tandoori naan","butter naan"], unit: "piece", kcal: 262, p: 8.7, c: 45, f: 5.1 },
  { id: 6,  name: "Bhatura",               aliases: ["bhatura","batura"], unit: "piece", kcal: 300, p: 7, c: 42, f: 12 },
  { id: 7,  name: "Rice (Cooked)",         aliases: ["rice","chawal","boiled rice","plain rice","steamed rice","white rice"], unit: "cup", kcal: 195, p: 4, c: 43, f: 0.4 },
  { id: 8,  name: "Biryani (Chicken)",     aliases: ["chicken biryani","biryani","murgh biryani","dum biryani"], unit: "plate", kcal: 450, p: 25, c: 55, f: 12 },
  { id: 9,  name: "Biryani (Veg)",         aliases: ["veg biryani","vegetable biryani","paneer biryani"], unit: "plate", kcal: 350, p: 10, c: 60, f: 8 },
  { id: 10, name: "Fried Rice",            aliases: ["fried rice","veg fried rice","egg fried rice","chinese rice"], unit: "plate", kcal: 320, p: 8, c: 52, f: 9 },
  { id: 11, name: "Upma",                  aliases: ["upma","rava upma","sooji upma"], unit: "bowl", kcal: 180, p: 4.5, c: 30, f: 5 },
  { id: 12, name: "Poha",                  aliases: ["poha","aval","beaten rice","pohaa","pohe"], unit: "bowl", kcal: 165, p: 4, c: 32, f: 3 },
  { id: 13, name: "Idli",                  aliases: ["idli","idly","steam idli"], unit: "piece", kcal: 58, p: 2, c: 12, f: 0.4 },
  { id: 14, name: "Dosa",                  aliases: ["dosa","plain dosa","sada dosa","dosai"], unit: "piece", kcal: 120, p: 3, c: 20, f: 3.5 },
  { id: 15, name: "Masala Dosa",           aliases: ["masala dosa","potato dosa","masala dosai"], unit: "piece", kcal: 220, p: 5, c: 36, f: 7 },
  { id: 16, name: "Sambar",                aliases: ["sambar","sambhar","south indian dal"], unit: "bowl", kcal: 80, p: 5, c: 12, f: 1.5 },
  { id: 17, name: "Dal Tadka",             aliases: ["dal","daal","yellow dal","tadka dal","toor dal","arhar dal","dal fry","dal tadka"], unit: "bowl", kcal: 180, p: 10, c: 28, f: 4 },
  { id: 18, name: "Dal Makhani",           aliases: ["dal makhani","makhani dal","kali dal","black dal","black lentil dal","urad dal"], unit: "bowl", kcal: 280, p: 12, c: 30, f: 12 },
  { id: 19, name: "Chole",                 aliases: ["chole","chana masala","chickpea curry","chhole","kabuli chana"], unit: "bowl", kcal: 270, p: 13, c: 40, f: 8 },
  { id: 20, name: "Rajma",                 aliases: ["rajma","kidney beans curry","rajma curry","red kidney beans"], unit: "bowl", kcal: 260, p: 14, c: 38, f: 6 },
  { id: 21, name: "Paneer Butter Masala",  aliases: ["paneer butter masala","paneer makhani","butter paneer","pbm"], unit: "bowl", kcal: 350, p: 18, c: 20, f: 22 },
  { id: 22, name: "Paneer Tikka Masala",   aliases: ["paneer tikka masala","paneer tikka curry"], unit: "bowl", kcal: 320, p: 20, c: 18, f: 20 },
  { id: 23, name: "Butter Chicken",        aliases: ["butter chicken","murgh makhani","chicken makhani","bc"], unit: "bowl", kcal: 320, p: 24, c: 12, f: 20 },
  { id: 24, name: "Chicken Curry",         aliases: ["chicken curry","chicken masala","murgh curry","desi chicken"], unit: "bowl", kcal: 280, p: 26, c: 8, f: 16 },
  { id: 25, name: "Egg Curry",             aliases: ["egg curry","anda curry","anda masala"], unit: "bowl", kcal: 220, p: 14, c: 8, f: 15 },
  { id: 26, name: "Fish Curry",            aliases: ["fish curry","machli curry","fish masala","meen curry"], unit: "bowl", kcal: 200, p: 22, c: 5, f: 10 },
  { id: 27, name: "Palak Paneer",          aliases: ["palak paneer","spinach paneer","saag paneer"], unit: "bowl", kcal: 250, p: 14, c: 12, f: 17 },
  { id: 28, name: "Aloo Sabzi",            aliases: ["aloo sabzi","potato curry","aloo ki sabzi","batata bhaji"], unit: "bowl", kcal: 180, p: 4, c: 28, f: 6 },
  { id: 29, name: "Mixed Veg Sabzi",       aliases: ["veg sabzi","mixed sabzi","sabzi","mixed vegetables","mix veg"], unit: "bowl", kcal: 120, p: 4, c: 16, f: 5 },
  { id: 30, name: "Pav Bhaji",             aliases: ["pav bhaji","pavbhaji","pao bhaji"], unit: "serving", kcal: 420, p: 10, c: 60, f: 16 },
  { id: 31, name: "Chai (with milk)",      aliases: ["chai","tea","masala chai","adrak chai","cutting chai","ginger tea","milk tea"], unit: "cup", kcal: 60, p: 2, c: 8, f: 2 },
  { id: 32, name: "Lassi (Sweet)",         aliases: ["lassi","sweet lassi","mango lassi","dahi lassi"], unit: "glass", kcal: 180, p: 6, c: 30, f: 4 },
  { id: 33, name: "Buttermilk",            aliases: ["chaas","buttermilk","masala chaas","mattha"], unit: "glass", kcal: 40, p: 3, c: 5, f: 0.5 },
  { id: 34, name: "Milk (Full Fat)",       aliases: ["milk","doodh","full fat milk","full cream milk","whole milk"], unit: "cup", kcal: 150, p: 8, c: 12, f: 8 },
  { id: 35, name: "Curd / Dahi",           aliases: ["dahi","curd","yoghurt","yogurt","plain dahi"], unit: "katori", kcal: 60, p: 3.5, c: 4.5, f: 3 },
  { id: 36, name: "Raita",                 aliases: ["raita","boondi raita","cucumber raita","dahi raita"], unit: "katori", kcal: 65, p: 3, c: 8, f: 2 },
  { id: 37, name: "Samosa",                aliases: ["samosa","samosa chaat","aloo samosa"], unit: "piece", kcal: 130, p: 2.5, c: 16, f: 6.5 },
  { id: 38, name: "Vada Pav",              aliases: ["vada pav","vada pao","batata vada pav"], unit: "piece", kcal: 290, p: 6, c: 42, f: 11 },
  { id: 39, name: "Dhokla",                aliases: ["dhokla","khaman dhokla","besan dhokla"], unit: "piece", kcal: 80, p: 4, c: 12, f: 1.5 },
  { id: 40, name: "Jalebi",                aliases: ["jalebi","jalebi fafda"], unit: "piece", kcal: 75, p: 0.8, c: 17, f: 1.5 },
  { id: 41, name: "Gulab Jamun",           aliases: ["gulab jamun","gulab jamun mithai"], unit: "piece", kcal: 150, p: 2, c: 27, f: 5 },
  { id: 42, name: "Halwa",                 aliases: ["halwa","sooji halwa","atta halwa","moong dal halwa"], unit: "katori", kcal: 250, p: 4, c: 36, f: 10 },
  { id: 43, name: "Egg (Boiled)",          aliases: ["boiled egg","anda","egg","hard boiled egg","soft boiled egg"], unit: "piece", kcal: 70, p: 6, c: 0.5, f: 5 },
  { id: 44, name: "Omelette",              aliases: ["omelette","egg omelette","masala omelette","anda omelette"], unit: "piece", kcal: 140, p: 10, c: 1, f: 11 },
  { id: 45, name: "Khichdi",               aliases: ["khichdi","dal khichdi","masala khichdi","moong khichdi"], unit: "bowl", kcal: 200, p: 8, c: 34, f: 4 },
  { id: 46, name: "Pongal",                aliases: ["pongal","ven pongal","khara pongal","rice pongal"], unit: "bowl", kcal: 220, p: 6, c: 38, f: 5 },
  { id: 47, name: "Curd Rice",             aliases: ["curd rice","dahi chawal","thayir sadam","mosaranna"], unit: "bowl", kcal: 180, p: 6, c: 30, f: 4 },
  { id: 48, name: "Ghee",                  aliases: ["ghee","desi ghee"], unit: "tsp", kcal: 45, p: 0, c: 0, f: 5, modifier: true },
  { id: 49, name: "Butter",                aliases: ["butter","amul butter","white butter","makhan","salted butter"], unit: "tsp", kcal: 36, p: 0, c: 0, f: 4, modifier: true },
  { id: 50, name: "Oil",                   aliases: ["oil","cooking oil","refined oil","sarson ka tel","mustard oil"], unit: "tsp", kcal: 45, p: 0, c: 0, f: 5, modifier: true },
  { id: 51, name: "Banana",                aliases: ["banana","kela","plantain"], unit: "medium", kcal: 105, p: 1.3, c: 27, f: 0.3 },
  { id: 52, name: "Apple",                 aliases: ["apple","seb"], unit: "medium", kcal: 78, p: 0.4, c: 21, f: 0.2 },
  { id: 53, name: "Orange",                aliases: ["orange","santra","mosambi","sweet lime"], unit: "medium", kcal: 62, p: 1.2, c: 15, f: 0.2 },
  { id: 54, name: "Mixed Fruit",           aliases: ["fruit salad","mixed fruit","fruits"], unit: "bowl", kcal: 80, p: 1, c: 19, f: 0.3 },
  { id: 55, name: "Sprouts",               aliases: ["sprouts","moong sprouts","mixed sprouts","germinated moong"], unit: "bowl", kcal: 85, p: 7, c: 14, f: 0.5 },
  { id: 56, name: "Peanuts",               aliases: ["peanuts","moongfali","groundnuts","roasted peanuts"], unit: "handful", kcal: 170, p: 7.5, c: 5, f: 14 },
  { id: 57, name: "Almonds",               aliases: ["almonds","badam","soaked almonds","almond nuts"], unit: "piece", kcal: 7, p: 0.3, c: 0.2, f: 0.6 },
  { id: 58, name: "Protein Shake",         aliases: ["protein shake","whey shake","protein smoothie","gym shake"], unit: "scoop", kcal: 120, p: 24, c: 3, f: 2 },
  { id: 59, name: "Bhel Puri",             aliases: ["bhel","bhelpuri","bhel puri","churmuri"], unit: "plate", kcal: 290, p: 6, c: 48, f: 8 },
  { id: 60, name: "Pani Puri",             aliases: ["pani puri","panipuri","golgappa","gol gappa","puchka","gupchup"], unit: "plate", kcal: 180, p: 3, c: 32, f: 5 },
  { id: 61, name: "Sev Puri",              aliases: ["sev puri","sevpuri","sev puri chaat"], unit: "plate", kcal: 320, p: 5, c: 42, f: 14 },
  { id: 62, name: "Dahi Puri",             aliases: ["dahi puri","dahipuri","dahi puri chaat"], unit: "plate", kcal: 280, p: 6, c: 38, f: 11 },
  { id: 63, name: "Papad",                 aliases: ["papad","papadum","appalam","roasted papad","fried papad"], unit: "piece", kcal: 50, p: 1.5, c: 7, f: 1.5 },
  { id: 64, name: "Biscuit",               aliases: ["biscuit","biscuits","marie biscuit","parle g","glucose biscuit","cookies"], unit: "piece", kcal: 40, p: 0.7, c: 6, f: 1.5 },
  { id: 65, name: "Rasam",                 aliases: ["rasam","charu","saaru","tomato rasam","pepper rasam"], unit: "bowl", kcal: 100, p: 3, c: 18, f: 2 },
  { id: 66, name: "Kadhi",                 aliases: ["kadhi","besan kadhi","kadhi pakoda","punjabi kadhi","gujarati kadhi"], unit: "bowl", kcal: 180, p: 6, c: 14, f: 11 },
  { id: 67, name: "Chole Bhature",         aliases: ["chole bhature","chole bhatura","chana bhatura","chole bhature plate"], unit: "plate", kcal: 650, p: 16, c: 80, f: 28 },
  { id: 68, name: "Chicken Breast",        aliases: ["chicken breast","grilled chicken","boiled chicken","tandoori chicken breast","skinless chicken","chicken breast piece"], unit: "100g", kcal: 165, p: 31, c: 0, f: 3.6 },
  { id: 69, name: "Paneer (Raw/Grilled)",  aliases: ["paneer","raw paneer","grilled paneer","tandoori paneer","paneer cubes"], unit: "100g", kcal: 265, p: 18, c: 4, f: 20 },
  { id: 70, name: "Tofu",                  aliases: ["tofu","soya paneer","bean curd"], unit: "100g", kcal: 145, p: 15, c: 3, f: 8 },
  { id: 71, name: "Egg Whites",            aliases: ["egg white","egg whites","boiled egg whites","anda safedi"], unit: "white", kcal: 17, p: 3.6, c: 0.2, f: 0.1 },
  { id: 72, name: "Bread (slice)",         aliases: ["bread","bread slice","white bread","brown bread","toast","slice of bread"], unit: "slice", kcal: 75, p: 3, c: 14, f: 1 },
  { id: 73, name: "Honey",                 aliases: ["honey","shahad","madh"], unit: "tbsp", kcal: 64, p: 0, c: 17, f: 0 },
  { id: 74, name: "Jam",                   aliases: ["jam","mixed fruit jam","strawberry jam","marmalade"], unit: "tbsp", kcal: 56, p: 0, c: 14, f: 0 },
  { id: 75, name: "Sugar",                 aliases: ["sugar","cheeni","chini","white sugar"], unit: "tsp", kcal: 16, p: 0, c: 4, f: 0 },
  { id: 76, name: "Lemon Rice",            aliases: ["lemon rice","chitranna","nimmakaya annam"], unit: "bowl", kcal: 250, p: 4, c: 45, f: 7 },
  { id: 77, name: "Mango",                 aliases: ["mango","aam","mangoes","alphonso"], unit: "medium", kcal: 150, p: 1.4, c: 38, f: 0.6 },
  { id: 78, name: "Guava",                 aliases: ["guava","amrud","peru"], unit: "medium", kcal: 68, p: 2.6, c: 14, f: 1 },
  { id: 79, name: "Papaya",                aliases: ["papaya","papita"], unit: "bowl", kcal: 60, p: 0.7, c: 15, f: 0.2 },
  { id: 80, name: "Watermelon",            aliases: ["watermelon","tarbooz","tarbuj"], unit: "bowl", kcal: 46, p: 0.9, c: 11, f: 0.2 },
  { id: 81, name: "Grapes",                aliases: ["grapes","angoor","angur"], unit: "bowl", kcal: 70, p: 0.7, c: 18, f: 0.2 },
  { id: 82, name: "Pomegranate",           aliases: ["pomegranate","anaar","anar"], unit: "bowl", kcal: 100, p: 2, c: 22, f: 1 },
  { id: 83, name: "Chikoo",                aliases: ["chikoo","sapota","sapodilla","chiku"], unit: "medium", kcal: 83, p: 0.4, c: 20, f: 1 },
  { id: 84, name: "Pineapple",             aliases: ["pineapple","ananas"], unit: "bowl", kcal: 74, p: 0.8, c: 19, f: 0.2 },
  { id: 85, name: "Custard Apple",         aliases: ["custard apple","sitaphal","sharifa"], unit: "medium", kcal: 100, p: 2, c: 24, f: 0.3 },
  { id: 86, name: "Cucumber",              aliases: ["cucumber","kheera","kakdi","kakri"], unit: "bowl", kcal: 16, p: 0.7, c: 4, f: 0.1 },
  { id: 87, name: "Carrot",                aliases: ["carrot","gajar"], unit: "medium", kcal: 25, p: 0.6, c: 6, f: 0.1 },
  { id: 88, name: "Tomato",                aliases: ["tomato","tamatar"], unit: "medium", kcal: 22, p: 1, c: 5, f: 0.2 },
  { id: 89, name: "Green Salad",           aliases: ["green salad","salad","kachumber","veg salad"], unit: "plate", kcal: 40, p: 2, c: 8, f: 0.5 },
  { id: 90, name: "Chicken Tikka",         aliases: ["chicken tikka","tandoori chicken","chicken tikka dry","murgh tikka"], unit: "piece", kcal: 55, p: 9, c: 1, f: 2 },
  { id: 91, name: "Paneer Tikka (dry)",    aliases: ["paneer tikka","paneer tikka dry","grilled paneer tikka"], unit: "piece", kcal: 70, p: 4, c: 2, f: 5 },
  { id: 92, name: "Roasted Chana",         aliases: ["roasted chana","bhuna chana","roasted chickpeas","chana snack","phutana"], unit: "handful", kcal: 120, p: 7, c: 20, f: 2 },
  { id: 93, name: "Uttapam",               aliases: ["uttapam","uthappam","rava uttapam","onion uttapam"], unit: "piece", kcal: 175, p: 4, c: 25, f: 6 },
  { id: 94, name: "Maggi",                 aliases: ["maggi","maggie","masala noodles","instant noodles","2 minute noodles"], unit: "pack", kcal: 350, p: 8, c: 50, f: 13 },
  { id: 95, name: "Pizza (slice)",         aliases: ["pizza","pizza slice","cheese pizza","veg pizza","margherita"], unit: "slice", kcal: 285, p: 12, c: 36, f: 10 },
  { id: 96, name: "Ice Cream",             aliases: ["ice cream","icecream","vanilla ice cream","kulfi","scoop of ice cream"], unit: "scoop", kcal: 140, p: 2.5, c: 16, f: 7 },
  { id: 97, name: "Matar Paneer",          aliases: ["matar paneer","mutter paneer","peas paneer","paneer matar"], unit: "bowl", kcal: 280, p: 14, c: 18, f: 16 },
  { id: 98, name: "Oats",                  aliases: ["oats","oatmeal","oats bowl","masala oats","overnight oats"], unit: "bowl", kcal: 150, p: 5, c: 27, f: 3, g: 40 },
  { id: 99, name: "Peanut Butter",         aliases: ["peanut butter","pb","moongfali butter"], unit: "tbsp", kcal: 95, p: 4, c: 3, f: 8 },
  { id: 100, name: "Soya Chunks",          aliases: ["soya chunks","soya nuggets","nutrela","meal maker","soya","soyabean chunks"], unit: "bowl", kcal: 170, p: 26, c: 18, f: 1.5, g: 50 },
  { id: 101, name: "Sweet Potato",         aliases: ["sweet potato","shakarkandi","shakarkand"], unit: "medium", kcal: 115, p: 2, c: 27, f: 0.2 },
  { id: 102, name: "Brown Rice",           aliases: ["brown rice","brown chawal"], unit: "cup", kcal: 215, p: 5, c: 45, f: 1.8 },
  { id: 103, name: "Greek Yogurt",         aliases: ["greek yogurt","hung curd","hung yogurt","chakka","greek yoghurt"], unit: "cup", kcal: 100, p: 10, c: 6, f: 0.5 },
  { id: 104, name: "Quinoa",               aliases: ["quinoa","quinoa bowl"], unit: "bowl", kcal: 220, p: 8, c: 39, f: 4 },
  { id: 105, name: "Protein Bar",          aliases: ["protein bar","energy bar","yogabar","protein cookie"], unit: "bar", kcal: 200, p: 20, c: 22, f: 7 },
  { id: 106, name: "Grilled Fish",         aliases: ["grilled fish","fish fillet","basa","tilapia","fish tikka","grilled fish fillet"], unit: "fillet", kcal: 180, p: 30, c: 1, f: 6 },
  { id: 107, name: "Low-Fat Paneer",       aliases: ["low fat paneer","low-fat paneer","diet paneer","toned paneer","skimmed paneer","low fat cottage cheese"], unit: "100g", kcal: 160, p: 20, c: 5, f: 7 },
  { id: 108, name: "Low-Fat Milk",         aliases: ["toned milk","skimmed milk","skim milk","double toned milk","low fat milk","low-fat milk"], unit: "cup", kcal: 100, p: 8, c: 12, f: 2.5 },
  { id: 109, name: "Low-Fat Curd",         aliases: ["low fat curd","low-fat curd","low fat dahi","low fat yogurt","greek yogurt low fat","skimmed curd"], unit: "katori", kcal: 45, p: 4, c: 5, f: 1 },
];

const FOOD_BY_ID = Object.fromEntries(FOODS.map(f => [f.id, f]));

module.exports = { FOODS, FOOD_BY_ID };
